import Foundation

extension String {
    /// Потокобезопасное получение локализованной строки.
    /// Если язык — "Русский", возвращает исходную строку без обращения к словарям.
    var localized: String {
        guard let currentLang = UserDefaults.standard.string(forKey: "sys_language"),
              currentLang != "Русский" && !currentLang.isEmpty else {
            return self
        }
        return Localizer.translate(self, to: currentLang)
    }
}

struct Localizer {
    /// Рекурсивная блокировка для защиты обращения к словарям из любых потоков (Data Race & Deadlock Prevention)
    private static let lock = NSRecursiveLock()
    
    private static let enTranslations: [String: String] = [
        // Экран параметров системы
        "Параметры системы": "System Settings",
        "Правовая информация и товарные знаки": "Legal Information & Trademarks",
        "SmartStock является независимым инструментом и не связан, не авторизован и не спонсируется Shutterstock, Adobe Stock, Getty Images, Depositphotos, Freepik, Alamy, Dreamstime, 123RF, Pond5 или Google. Все товарные знаки и названия брендов принадлежат их правообладателям.": "SmartStock is an independent software tool and is not affiliated with, authorized, maintained, sponsored, or endorsed by Shutterstock, Adobe Stock, Getty Images, Depositphotos, Freepik, Alamy, Dreamstime, 123RF, Pond5, or Google. All trademarks, service marks, and brand names belong to their respective owners.",
        "Интерфейс": "Interface",
        "Интерфейс и Оформление": "Interface & Appearance",
        "Автозагрузка папки (Планировщик)": "Folder Auto-upload (Scheduler)",
        "Параметры выгрузки и очередность": "Upload Parameters & Priority",
        "Память и Очистка кэша": "Storage & Cache Management",
        "Язык приложения": "App Language",
        "ОБЛАКО GOOGLE ФОТО": "GOOGLE PHOTOS CLOUD",
        "Google Фото и Drive": "Google Photos & Drive",
        "Параметры Google Фото": "Google Photos Settings",
        "Подключить": "Connect",
        "Подключено к Google Фото": "Connected to Google Photos",
        "Не подключено": "Not Connected",
        "Импорт видео и фото из архива Google Фото": "Import videos and photos from Google Photos archive",
        "Выход из Google Фото выполнен": "Signed out of Google Photos",
        "Ваш Client ID из Google Cloud Console...": "Your Client ID from Google Cloud Console...",
        "Вставьте Client ID из Google Cloud Console...": "Paste Client ID from Google Cloud Console...",
        "Google OAuth Client ID": "Google OAuth Client ID",
        "Google OAuth Client ID (необязательно)": "Google OAuth Client ID (optional)",
        "Используется для прямого доступа к API Google Фото и Drive.": "Used for direct access to Google Photos and Drive APIs.",
        "Интеллектуальный Помощник": "Intelligent Assistant",
        "Настройте ИИ для мгновенной индексации ваших кадров. Генерация коммерческих названий и SEO-тегов.": "Configure AI for instant indexing of your shots. Generation of commercial titles and SEO tags.",
        "ИИ провайдеры": "AI Providers",
        "Введите личный токен аутентификации API": "Enter your personal API auth token",
        "Вставьте ключ API...": "Paste API key...",
        "Промпт для ИИ-анализа": "AI Analysis Prompt",
        "Подключение Google Фото": "Connect Google Photos",
        "Выбирайте исходные видео и фото прямо из вашего облачного архива для публикации на стоках.": "Select original videos and photos directly from your cloud archive for stock submission.",
        "Открытие окна авторизации Google...": "Opening Google authorization window...",
        "Пожалуйста, введите ваш Google Client ID в параметрах системы.": "Please enter your Google Client ID in system settings.",
        "Успешная авторизация в Google": "Successfully authorized with Google",
        "Отключено от Google Фото": "Disconnected from Google Photos",
        "Настройка Google Фото": "Google Photos Setup",
        "Пошаговое руководство по получению Client ID": "Step-by-step guide to obtaining Client ID",
        "Создайте проект в Google Cloud": "Create a Project in Google Cloud",
        "Перейдите в консоль разработчика Google Cloud и создайте новый бесплатный проект (например, SmartStock).": "Go to Google Cloud Developer Console and create a new free project (e.g., SmartStock).",
        "Включите Photos Library API": "Enable Photos Library API",
        "В разделе «APIs & Services» → «Library» найдите «Photos Library API» (а также «Google Drive API») и нажмите кнопку «Enable» (Включить).": "In 'APIs & Services' → 'Library', find 'Photos Library API' (and 'Google Drive API') and click 'Enable'.",
        "Настройте OAuth Consent Screen": "Configure OAuth Consent Screen",
        "В разделе «OAuth consent screen» выберите тип «External» (Внешний), укажите имя приложения и ваш email. В блоке «Test users» добавьте свой Gmail-адрес.": "In 'OAuth consent screen', select 'External', enter app name and your email. In 'Test users', add your Gmail address.",
        "Создайте OAuth Client ID": "Create OAuth Client ID",
        "В разделе «Credentials» нажмите «+ Create Credentials» → «OAuth client ID». Выберите тип приложения «iOS» (Bundle ID: com.samvel.smartstock.SmartStock) или «Web application».": "In 'Credentials', click '+ Create Credentials' → 'OAuth client ID'. Select application type 'iOS' (Bundle ID: com.samvel.smartstock.SmartStock) or 'Web application'.",
        "Вставьте Client ID в приложение": "Paste Client ID into App",
        "Скопируйте полученный идентификатор (вида xxxx.apps.googleusercontent.com) и вставьте в поле Client ID в приложении.": "Copy the generated identifier (like xxxx.apps.googleusercontent.com) and paste into the Client ID field in the app.",
        "Открыть Google Cloud Console": "Open Google Cloud Console",
        "Инструкция Google Фото": "Google Photos Guide",
        "Как получить API-ключ": "How to Get API Key",
        "Бесплатно": "Free",
        "Рекомендуемый провайдер: самый быстрый и бесплатный доступ.": "Recommended provider: fastest and free access.",
        "Откройте Google AI Studio": "Open Google AI Studio",
        "Перейдите на официальный портал Google AI Studio (aistudio.google.com).": "Go to the official Google AI Studio portal (aistudio.google.com).",
        "Войдите с Google-аккаунтом": "Sign in with Google Account",
        "Используйте ваш обычный личный аккаунт Google для входа в сервис.": "Use your regular personal Google account to sign in.",
        "Нажмите «Create API key»": "Click 'Create API key'",
        "Нажмите синюю кнопку «Create API key» (Создать ключ API) и выберите или создайте проект.": "Click the blue 'Create API key' button and select or create a project.",
        "Скопируйте и вставьте ключ": "Copy and Paste Key",
        "Скопируйте сгенерированный ключ (начинается на «AIzaSy...») и вставьте в приложении в поле Gemini.": "Copy the generated key (starts with 'AIzaSy...') and paste it into the Gemini field in the app.",
        "Получить ключ в Google AI Studio": "Get Key in Google AI Studio",
        "Высокое качество индексации через модели GPT-4o и GPT-4o-mini.": "High-quality indexing via GPT-4o and GPT-4o-mini models.",
        "Откройте OpenAI Platform": "Open OpenAI Platform",
        "Перейдите на страницу ключей API (platform.openai.com/api-keys).": "Go to the API keys page (platform.openai.com/api-keys).",
        "Создайте новый секретный ключ": "Create New Secret Key",
        "Нажмите кнопку «+ Create new secret key», укажите название и сохраните ключ.": "Click '+ Create new secret key', enter a name and save the key.",
        "Вставьте ключ в приложение": "Paste Key into App",
        "Скопируйте ключ (начинается на «sk-...») и вставьте в поле OpenAI в настройках ИИ.": "Copy the key (starts with 'sk-...') and paste it into the OpenAI field in AI settings.",
        "Открыть OpenAI API Keys": "Open OpenAI API Keys",
        "Глубокое понимание коммерческой эстетики через Claude 3.5 Sonnet.": "Deep understanding of commercial aesthetics via Claude 3.5 Sonnet.",
        "Откройте Anthropic Console": "Open Anthropic Console",
        "Перейдите на страницу ключей (console.anthropic.com/settings/keys).": "Go to the keys page (console.anthropic.com/settings/keys).",
        "Создайте API-ключ": "Create API Key",
        "Нажмите «Create Key», задайте имя и скопируйте сформированный токен.": "Click 'Create Key', specify a name and copy the generated token.",
        "Скопируйте ключ (начинается на «sk-ant-...») и вставьте в поле Claude в настройках ИИ.": "Copy the key (starts with 'sk-ant-...') and paste it into the Claude field in AI settings.",
        "Открыть Anthropic Console": "Open Anthropic Console",
        "Импортировать в очередь": "Import to Queue",
        "Медиафайлов не найдено. Проверьте, включен ли Photos/Drive API в Google Cloud.": "No media files found. Check if Photos/Drive API is enabled in Google Cloud.",
        "Подписка": "Subscription",
        "Связь с App Store...": "Connecting to App Store...",
        "Восстановить": "Restore",
        "Максимум продаж на стоках": "Maximize Your Microstock Sales",
        "Автоматизируйте рутину и отправляйте сотни фото и видео на 10+ стоков в один клик.": "Automate the routine and submit hundreds of photos and videos to 10+ stock agencies in one click.",
        "Безлимитный ИИ-анализ кадра": "Unlimited AI Media Analysis",
        "Генерация коммерческих названий, описаний и до 50 тегов через Gemini 2.5, GPT-4o, Claude": "Generate commercial titles, descriptions and up to 50 tags via Gemini 2.5, GPT-4o, Claude",
        "Выгрузка на все 10+ стоков сразу": "Simultaneous Upload to 10+ Stocks",
        "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime и др.": "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime & more.",
        "Безлимитная очередь файлов": "Unlimited File Queue",
        "Пакетная обработка и загрузка сотен фото и 4K/8K видео без пауз и ограничений": "Batch process and upload hundreds of photos and 4K/8K videos without limits",
        "Google Фото и Google Диск": "Google Photos & Google Drive",
        "Неограниченный импорт исходных медиафайлов прямо из облака": "Unlimited direct import of media files from cloud storage",
        "Экспорт CSV и метаданных": "CSV & Metadata Export",
        "Мгновенное создание таблиц метаданных для любых агентств": "Instant metadata spreadsheet creation for any agency",
        "ВЫГОДА 50% • 3 ДНЯ БЕСПЛАТНО": "50% OFF • 3 DAYS FREE",
        "Годовая подписка": "Yearly Subscription",
        "Всего ~249 ₽ в месяц. Списание после 3-дневного триала.": "Save 50%. Billed annually after 3-day free trial.",
        "Месячная подписка": "Monthly Subscription",
        "Ежемесячный доступ со всеми обновлениями.": "Monthly access with all updates included.",
        "НАВСЕГДА": "LIFETIME",
        "Пожизненный PRO": "Lifetime PRO",
        "Один платёж раз и навсегда. Без подписок.": "One-time payment forever. No recurring charges.",
        "Попробовать 3 дня бесплатно": "Try 3 Days Free",
        "Продолжить с SmartStock PRO": "Continue with SmartStock PRO",
        "Подписка продлевается автоматически, пока не будет отменена в настройках Apple ID не менее чем за 24 часа до окончания текущего периода.": "Subscription automatically renews unless canceled in Apple ID Settings at least 24 hours before the end of the current period.",
        "Условия использования (EULA)": "Terms of Use (EULA)",
        "Политика конфиденциальности": "Privacy Policy",
        "Поздравляем! SmartStock PRO успешно активирован! 🎉": "Congratulations! SmartStock PRO is now active! 🎉",
        "Не удалось подключиться к App Store. Пожалуйста, проверьте интернет-соединение.": "Could not connect to App Store. Please check your internet connection.",
        "Ваши покупки успешно восстановлены! Доступ к SmartStock PRO открыт.": "Your purchases have been successfully restored! SmartStock PRO is active.",
        "Активных подписок не найдено. Если вы совершали покупку, убедитесь, что вошли под нужным Apple ID.": "No active subscriptions found. If you previously purchased, ensure you are signed into the correct Apple ID.",
        "АКТИВЕН": "ACTIVE",
        "Все премиум-функции и безлимитный ИИ активны": "All premium features and unlimited AI are active",
        "Перейти на SmartStock PRO": "Upgrade to SmartStock PRO",
        "Безлимитный ИИ, 10+ стоков и автозагрузка": "Unlimited AI, 10+ stocks & auto-upload",
        "В бесплатной версии доступно до 2 стоков. Перейдите на PRO для одновременной выгрузки на все стоки!": "Free tier allows up to 2 stocks. Upgrade to PRO to upload to all stocks simultaneously!",
        "Динамика загрузок": "Upload Dynamics",
        "Сводка активности": "Activity Summary",
        "История выгрузок": "Upload History",
        "По стокам": "By Stock Agency",
        "подключено": "connected",
        "История пуста": "History is empty",
        "Очистить историю": "Clear History",
        "Очистить историю?": "Clear history?",
        "Вся история загрузок будет удалена. Это действие нельзя отменить.": "All upload history will be deleted. This action cannot be undone.",
        "Очистить": "Clear",
        "Недавние": "Recent",
        "Порядок": "Reorder",
        "Выбрать": "Select",
        "Поиск фото, альбомов...": "Search photos, albums...",
        "Статистика очереди": "Queue Stats",
        "Всего": "Total",
        "всего": "total",
        "загрузок": "uploads",
        "готовность": "ready",
        "Покупки": "Sales",
        "Синхронизация": "Sync",
        "Активно": "Active",
        "Нет данных": "No data",
        "Демо": "Demo",
        "Все стоки": "All Stocks",
        "Загрузки": "Uploads",
        "Успешно": "Success",
        "Ошибок": "Errors",
        "Ошибки": "Errors",
        "Фото": "Photos",
        "Видео": "Videos",
        "Ок": "OK",
        "Язык интерфейса": "App Language",
        "Тема оформления": "Theme",
        "Темная": "Dark",
        "Светлая": "Light",
        "Системная": "System",
        "Предел частоты кадров": "Frame Rate Limit",
        "Планировщик": "Scheduler",
        "Фоновый планировщик выгрузки": "Background Upload Scheduler",
        "При активации планировщика система будет проверять новые фото и отправлять их в фоновом режиме.": "When activated, the system will check for new photos and upload them in the background.",
        "Папка для импорта": "Import Folder",
        "Выбрать...": "Select...",
        "Интервал проверки": "Check Interval",
        "Каждые": "Every",
        "Еще не запускался": "Never ran",
        "Запуск проверки...": "Running check...",
        "Запустить проверку сейчас": "Run Check Now",
        "При активации планировщика система будет проверять новые фото в выбранной папке и отправлять их в фоновом режиме.": "When activated, the system will check for new photos in the selected folder and upload them in the background.",
        "Проверка папки завершена!": "Folder check completed!",
        "Не удалось получить доступ к папке": "Could not access the folder",
        "Папка успешно выбрана: ": "Folder successfully selected: ",
        "Ошибка сохранения папки: ": "Error saving folder: ",
        "Планировщик выгрузки": "Upload Scheduler",
        "Фоновая обработка завершена. Новых файлов загружено: ": "Background processing completed. New files uploaded: ",
        "час": "hour",
        "часа": "hours",
        "часов": "hours",
        "Автоматический Апскейл": "Auto Upscale",
        "Включить авто-апскейл": "Enable Auto-Upscale",
        "Порог срабатывания": "Trigger Threshold",
        "Коэффициент (масштаб)": "Scale Factor",
        "В очереди": "In Queue",
        "В ОЧЕРЕДИ": "IN QUEUE",
        "ГОТОВ": "READY",
        "Удалить": "Delete",
        "Отправить": "Send",
        "Отправлено": "Sent",
        "Все файлы": "All files",
        "Только фото": "Photos only",
        "Только видео": "Videos only",
        "Подготовка воспроизведения видео...": "Preparing video playback...",
        "Фотография Google Фото": "Google Photo",
        "Видеозапись Google Фото": "Google Video",
        "Параметры выгрузки": "Upload Parameters",
        "Потоки параллельной загрузки": "Parallel Upload Streams",
        "Загрузка видео по очереди": "Sequential video upload",
        "Видеофайлы будут отправляться строго по одному друг за другом для стабильности FTP.": "Video files will be uploaded strictly one by one to ensure FTP stability.",
        "Загрузка фото по очереди": "Sequential photo upload",
        "Фотографии будут отправляться строго по одной по очереди.": "Photo files will be uploaded strictly one by one in sequence.",
        "Загрузка видео по очереди включена": "Sequential video upload enabled",
        "Загрузка видео по очереди отключена": "Sequential video upload disabled",
        "Загрузка фото по очереди включена": "Sequential photo upload enabled",
        "Загрузка фото по очереди отключена": "Sequential photo upload disabled",
        "Автоповтор при сбоях": "Auto-retry on failures",
        "Сжатие JPEG перед загрузкой": "Compress JPEG before upload",
        "Системные уведомления": "System Notifications",
        "Локальный ПК-сервер": "Local PC Server",
        "Google OAuth Client ID (необязательно)": "Google OAuth Client ID (optional)",
        "Если в окне Google выводится 'invalid_client (401)', введите ваш свой Client ID из Google Cloud Console (APIs & Services -> Credentials).": "If Google shows 'invalid_client (401)', enter your own Client ID from Google Cloud Console (APIs & Services -> Credentials).",
        "Загрузка через ПК-сервер": "Upload via PC Server",
        "Адрес сервера (IP:Порт)": "Server Address (IP:Port)",
        "Позволяет отправлять фото через программу на вашем компьютере. Полезно, если на телефоне блокируется FTPS к Shutterstock.": "Allows sending photos via the app on your computer. Useful if FTPS to Shutterstock is blocked on the phone.",
        "Облачная синхронизация": "Cloud Sync",
        "Синхронизация профиля активна": "Profile sync is active",
        "Выйти": "Sign Out",
        "Войдите в аккаунт, чтобы синхронизировать ваши настройки стоков и ключи API в облаке.": "Sign in to synchronize your stock settings and API keys in the cloud.",
        "Вход с Google": "Sign in with Google",
        "Сохранить все настройки": "Save All Settings",
        
        // Экран стоков
        "Интегрированные фотостоки": "Integrated Stock Agencies",
        "Настройки стоков": "Stock Settings",
        "Проверка соединения...": "Verifying connection...",
        "Настроен": "Configured",
        "Нужна настройка": "Setup required",
        "Параметры SFTP / FTP для": "SFTP / FTP parameters for",
        "Активен": "Active",
        "Имя пользователя (логин)": "Username (login)",
        "Пароль": "Password",
        "Дополнительные параметры сервера": "Advanced Server Parameters",
        "Имя хоста (сервер)": "Hostname (server)",
        "Проверить соединение": "Test Connection",
        "Проверка...": "Testing...",
        "Готово": "Done",
        "Подключение": "Connection",
        "Пожалуйста, введите логин и пароль.": "Please enter username and password.",
        
        // Вкладки таб-бара
        "Очередь": "Queue",
        "ИИ-Ассистент": "AI Assistant",
        "Стоки": "Stocks",
        "Параметры": "Settings",
        "Галерея": "Gallery",
        "ИИ": "AI Engines",
        "Статистика": "Insights",
        "Агентства": "Agencies",
        "Настройки": "Settings",
        "Общий баланс": "Total Balance",
        "За последние 30 дней": "Last 30 Days",
        "Ожидает подтверждения": "Pending Approval",
        "История доходов": "Earnings History",
        "Эффективность агентств": "Performance by Agency",
        "Показать все": "View All",
        "Проверено": "Approved",
        "В ожидании": "Pending",
        "На удержании": "On Hold",
        "Синхронизация: ": "Sync: ",
        "2 ч. назад": "2h ago",
        "5 ч. назад": "5h ago",
        "12 ч. назад": "12h ago",
        "1 д. назад": "1d ago",
        "Вошли через Google или Apple?": "Signed in with Google or Apple?",
        "Важно для Google / Apple": "Important for Google / Apple",
        "Если вы регистрировались на фотостоках через аккаунт Google или Apple, прямой вход по паролю этих сервисов не поддерживается для FTP/SFTP загрузки (это техническое ограничение самих стоков).": "If you registered on stock agencies via a Google or Apple account, direct login using their password is not supported for FTP/SFTP upload (this is a technical limitation of the stock agencies themselves).",
        "Для выгрузки из приложения вам необходимо использовать специальный FTP-пароль, сгенерированный в личном кабинете автора.": "To upload from the app, you need to use a special FTP password generated in your contributor dashboard.",
        "Инструкция для Adobe Stock": "Adobe Stock Instructions",
        "1. Войдите в личный кабинет автора на contributor.adobestock.com.": "1. Log in to the contributor dashboard at contributor.adobestock.com.",
        "2. Перейдите в 'Настройки учетной записи' (нажав на свой профиль в правом верхнем углу).": "2. Go to 'Account Settings' (by clicking on your profile in the top-right corner).",
        "3. В подразделе 'Настройки FTP' вы увидите ваш персональный логин (ID) и сгенерированный FTP-пароль.": "3. Under the 'FTP Settings' sub-section, you will see your personal username (ID) and generated FTP password.",
        "4. Вставьте эти данные в настройки Adobe Stock в приложении.": "4. Paste these credentials into the Adobe Stock settings in the app.",
        "Открыть Adobe Stock Contributor": "Open Adobe Stock Contributor",
        "Инструкция для Shutterstock": "Shutterstock Instructions",
        "1. Войдите в кабинет автора на submit.shutterstock.com.": "1. Log in to the contributor dashboard at submit.shutterstock.com.",
        "2. Перейдите в настройки аккаунта 'Account Settings'.": "2. Go to 'Account Settings'.",
        "3. Найдите раздел FTP и скопируйте предоставленные учетные данные (обычно логином является ваш email).": "3. Locate the FTP section and copy the provided credentials (typically your email is the username).",
        "4. Введите их в настройки Shutterstock в приложении.": "4. Enter them into the Shutterstock settings in the app.",
        "Открыть submit.shutterstock.com": "Open submit.shutterstock.com",
        "Вход через Google / Apple": "Sign in with Google / Apple",
        
        // Экран очереди загрузки
        "Очередь выгрузки": "Upload Queue",
        "Готовы к загрузке": "Ready to upload",
        "Загружено": "Uploaded",
        "Ошибки": "Errors",
        "Добавить фото": "Add Photos",
        "Загрузить все": "Upload All",
        "ИИ Анализ": "AI Analysis",
        "Редактировать": "Edit",
        "Настройки стоков для фото": "Stock settings for photo",
        "Файл": "File",
        "Размер": "Size",
        "Статус": "Status",
        "Загрузить новый контент": "Upload New Content",
        "Нажмите для выбора или перетащите": "Tap to browse or drop here",
        "Поиск фото, альбомов...": "Search photos, albums...",
        "Недавние": "Recents",
        "Выбрать": "Select",
        "Очередь пуста": "Queue is empty",
        "Выберите снимки, чтобы запустить ИИ-подбор метаданных и отправить их на микростоки.": "Select photos to start AI metadata generation and upload to microstocks.",
        "Запустить ИИ-анализ": "Run AI Analysis",
        "Выгрузить на стоки": "Upload to Stocks",
        "ИИ для выбранных": "AI for Selected",
        "Отправить выбр.": "Upload Selected",
        "Заполнить все ИИ": "Fill All with AI",
        "Порядок очереди": "Queue Order",
        "Ключевые слова отсутствуют. Запустите ИИ-анализ.": "No keywords found. Run AI analysis.",
        "Отправить на стоки": "Send to Stocks",
        "Заполнить ИИ": "Fill with AI",
        "Выбрать стоки...": "Select Stocks...",
        "Удалить из очереди": "Remove from Queue",
        "Подробнее": "Details",
        "Скопировать": "Copy",
        "Закрыть": "Close",
        
        // ИИ-Ассистент
        "Интеллектуальный ассистент": "AI Assistant",
        "Интеллектуальный Помощник": "Intelligent Assistant",
        "Генерация ключевых слов и описаний с помощью ИИ": "AI Keywording and Description Generator",
        "Настройте ИИ для мгновенной индексации ваших кадров. Генерация коммерческих названий и SEO-тегов.": "Configure AI for instant indexing of your frames. Generation of commercial titles and SEO tags.",
        "ИИ провайдеры": "AI Providers",
        "Параметры подключения": "Connection Parameters",
        "Введите личный токен аутентификации API": "Enter your personal API authentication token",
        "Вставьте ключ API...": "Paste API key...",
        "Промпт для ИИ-анализа": "Prompt for AI Analysis",
        "Промпт определяет формат возвращаемого JSON-файла с заголовком и ключевыми словами.": "The prompt specifies the structure of the JSON file containing title and keywords.",
        "Анализ изображения": "Analyze Image",
        "Результаты анализа": "Analysis Results",
        "Название": "Title",
        "Описание": "Description",
        "Ключевые слова": "Keywords",
        "Категории": "Categories",
        "Скопировать все": "Copy All",
        "Применить к фото": "Apply to Photo",
        "Стандартный": "Standard",
        "Коммерческий": "Commercial",
        "Репортажный": "Editorial",
        "Креативный": "Creative",
        "SEO-Максимум": "SEO Max",
        "Мини": "Mini",
        "Не настроен": "Not Configured",
        "Проверка ключа": "Key Verification",
        "Пожалуйста, введите API-ключ перед проверкой.": "Please enter an API key before verifying.",
        
        // Экран редактирования метаданных
        "Метаданные": "Metadata",
        "Заголовок": "Title",
        "Заново": "Regenerate",
        "Заголовок фото": "Photo title",
        "Добавить слово": "Add keyword",
        "Добавить": "Add",
        "Категории (Макс. 2)": "Categories (Max 2)",
        "Лимит достигнут": "Limit reached",
        "Категории не выбраны. Выберите до 2 категорий.": "No categories selected. Choose up to 2 categories.",
        "Сохранить изменения": "Save Changes",
        
        // Экран статистики
        "Все стоки": "All Stocks",
        "Метрики": "Metrics",
        "Загрузки": "Uploads",
        "Успешно": "Success",
        "Покупки": "Sales",
        "Ошибок": "Errors",
        "Синхронизация": "Sync",
        "Динамика загрузок": "Upload Dynamics",
        "Демо": "Demo",
        "Активно": "Active",
        "Нет данных": "No Data",
        "История загрузок": "Upload History",
        "записей": "records",
        "История пуста": "History is empty",
        "Очистить историю": "Clear History",
        "Очистить": "Clear",
        "Вся история загрузок будет удалена. Это действие нельзя отменить.": "All upload history will be deleted. This action cannot be undone.",
        "По стокам": "By Stock",
        "подключено": "connected",
        "Нет загрузок": "No uploads",
        "Нет подключённых стоков": "No connected stock agencies",
        "Перейдите в раздел «Агентства» и настройте учётные данные для Shutterstock, Adobe Stock или других стоков — статистика загрузок появится здесь автоматически.": "Go to Agencies section and configure credentials for Shutterstock, Adobe Stock or other stocks — upload statistics will appear here automatically.",
        "Перейти в настройки агентств →": "Go to agency settings →",
        
        // Новые переводы для настроек
        "Меньше 4 МБ (Рекомендуется)": "Less than 4 MB (Recommended)",
        "Меньше 2 МБ": "Less than 2 MB",
        "Меньше 8 МБ": "Less than 8 MB",
        "Увеличение 2x (Бикубическое)": "Scale 2x (Bicubic)",
        "Увеличение 4x (Нейросеть)": "Scale 4x (Neural Network)",
        "120 FPS (Ультра-плавность)": "120 FPS (Ultra-smooth)",
        "60 FPS (Стандартный)": "60 FPS (Standard)",
        "30 FPS (Энергосбережение)": "30 FPS (Power Saving)",
        "Русский": "Russian",
        "English": "English",
        "Настройки сохранены!": "Settings saved!",
        "Настройки успешно сохранены!": "Settings successfully saved!",
        "Успешный вход через Apple!": "Successfully signed in with Apple!",
        "Успешный вход через Google!": "Successfully signed in with Google!",
        "Частота кадров: ": "Frame rate: ",
        " — применится при запуске": " — will apply on restart",
        "Параллельные потоки: ": "Parallel streams: ",
        " — применится при следующей загрузке": " — will apply on next upload",
        "Авто-апскейл включён — работает при добавлении фото": "Auto-upscale enabled — works when adding photos",
        "Авто-апскейл отключён": "Auto-upscale disabled",
        "Язык изменён на Русский": "Language changed to Russian",
        "Language changed to English": "Language changed to English",
        "поток": "stream",
        "потока": "streams",
        "потоков": "streams",
        "Авторизация...": "Signing in...",
        
        // Экран настроек стоков
        "Успешное соединение с сервером": "Successfully connected to server",
        "Ошибка соединения с": "Connection error with",
        "Внимание: Данный сток требует SFTP. Plain FTP-соединение для него может быть недоступно.": "Warning: This stock requires SFTP. Plain FTP connection may not be available.",
        
        // Вход и справка
        "Вход через": "Sign in via",
        "Введите вашу электронную почту для синхронизации аккаунта.": "Enter your email address to synchronize your account.",
        "Адрес электронной почты": "Email Address",
        "Продолжить": "Continue",
        "Безопасное соединение по стандарту OAuth 2.0": "Secure connection via OAuth 2.0 standard",
        "Отмена": "Cancel",
        "Инструкция по настройке FTP для": "FTP setup instructions for",
        "Из буфера": "From Clipboard",
        "Сканировать": "Scan",
        "Импортировать": "Import",
        "Обнаружены данные для настройки": "Configuration credentials detected for",
        
        // Новые переводы для Очереди
        "Ошибка: Нет активных стоков или не введены логин/пароль!": "Error: No active stock agencies configured or credentials missing!",
        "Загрузка файла": "Uploading file",
        "Нет файлов, готовых к отправке.": "No files ready for upload.",
        "успешно загружен на стоки!": "successfully uploaded to stocks!",
        "Ошибка выгрузки": "Upload error",
        "успешно загружен!": "successfully uploaded!",
        "Ошибка:": "Error:",
        "Успешная выгрузка": "Upload Successful",
        "Нажмите на агентство ниже, чтобы зайти в личный кабинет через встроенный браузер.": "Tap on an agency below to log in to your account via the built-in browser.",
        "ИИ АНАЛИЗ": "AI ANALYZE",
        "Анализируем...": "Analyzing...",
        "Ваш умный микростоковый менеджер": "Your smart microstock manager",
        "Вход в систему": "Sign In",
        "Регистрация": "Register",
        "Email": "Email",
        "Зарегистрироваться": "Register",
        "Войти": "Sign In",
        "или": "or",
        "У вас нет аккаунта?": "Don't have an account?",
        "Уже есть аккаунт?": "Already have an account?",
        "Введите ваш Email": "Please enter your Email",
        "Введите ваш пароль": "Please enter your password",
        "Некорректный формат Email": "Invalid Email format",
        "Пароль должен содержать не менее 6 символов": "Password must contain at least 6 characters",
        "Мой аккаунт": "My Account",
        "Выйти из аккаунта": "Sign Out",
        "Вы уверены, что хотите выйти из аккаунта?": "Are you sure you want to sign out?",
        "Частота кадров изменена на ": "Frame rate changed to ",
        "Статистика очереди": "Queue Stats",
        "Всего": "Total",
                "Автозагрузка папки (Планировщик)": "Auto-upload Folder (Scheduler)",
        "Автоповтор при сбоях (3 попытки)": "Auto-retry on failures (3 attempts)",
        "Без названия": "Untitled",
        "Видеофайлы отправляются строго по очереди один за другим без перегрева процессора.": "Video files are uploaded strictly one by one to avoid CPU overheating.",
        "Войти через Помощник (авто-настройка)": "Sign in via Assistant (auto-setup)",
        "Выбирайте исходные видео и фото прямо из вашего облачного архива для публикации на стоках.": "Select original videos and photos directly from your cloud library to publish on microstocks.",
        "Высокий": "High",
        "Демо-описание: Живописный закат солнца над горным хребтом.": "Demo description: Scenic sunset over a mountain range.",
        "Драматичный закат в горах (Демо)": "Dramatic Sunset in Mountains (Demo)",
        "Загрузка видео по очереди (Строго 1 за 1)": "Sequential video upload (Strictly 1 by 1)",
        "Загрузка медиафайлов...": "Loading media files...",
        "Загрузка...": "Loading...",
        "Запущен ИИ-анализ для": "AI analysis started for",
        "ИИ успешно заполнил метаданные для": "AI successfully generated metadata for",
        "Изменить": "Change",
        "Интерфейс и Оформление": "Interface & Design",
        "Использовано диска:": "Disk space used:",
        "КЛЮЧЕВЫЕ СЛОВА (Генерация ИИ)": "KEYWORDS (AI Generation)",
        "Кэш скачанных медиафайлов очищен!": "Downloaded media cache cleared!",
        "Кэширование включено": "Caching enabled",
        "МЕТАДАННЫЕ": "METADATA",
        "Началась отправка": "Started uploading",
        "Не выбрана": "Not selected",
        "Не подключено": "Not connected",
        "Нет новых файлов для ИИ-анализа.": "No new files for AI analysis.",
        "Обмен кода авторизации...": "Exchanging auth code...",
        "Описание отсутствует": "No description",
        "Очистить историю?": "Clear history?",
        "Очистка остаточного кэша": "Clear residual cache",
        "Ошибка ИИ-анализа для": "AI analysis error for",
        "Ошибка сохранения папки:": "Error saving folder:",
        "ПРОГНОЗ ПОПУЛЯРНОСТИ (Рыночный анализ ИИ)": "POPULARITY PREDICTION (AI Market Analysis)",
        "Память и Очистка кэша": "Storage & Cache Cleanup",
        "Папка для сканирования": "Scan Folder",
        "Папка успешно выбрана:": "Folder successfully selected:",
        "Параллельные потоки:": "Parallel streams:",
        "Параметры выгрузки и очередность": "Upload Parameters & Sequence",
        "Подключено": "Connected",
        "Подключить": "Connect",
        "Позволяет отправлять фото через программу на вашем компьютере.": "Allows sending photos via the program on your computer.",
        "Поиск по файлам...": "Search files...",
        "Последний запуск": "Last run",
        "Приложение работает как прямой проводник: файлы отправляются без дублирования на диск телефона.": "The app operates as a direct explorer: files are uploaded without duplicating to device storage.",
        "Проверка подключения к": "Verifying connection to",
        "Режим проводника (Прямая выгрузка без кэша)": "Explorer Mode (Direct upload without cache)",
        "Режим проводника активен: 0 МБ кэша": "Explorer mode active: 0 MB cache",
        "Сервер выгрузки:": "Upload server:",
        "Синхронизация:": "Sync:",
        "Статус:": "Status:",
        "Учетные данные обнаружены": "Credentials detected",
        "Файлы на устройстве": "Device Files",
        "Файлы не найдены": "Files not found",
        "Фоновый авто-сканер": "Background auto-scanner",
        "Фотографии будут отправляться строго последовательно по одной.": "Photos will be uploaded strictly one by one.",
        "Язык приложения": "App Language",
        "всего": "total",
        "загрузок": "uploads",
        "из": "of",
        "файлов...": "files...",
        "Фото": "Photos",
        "Видео": "Videos",
        "Порядок": "Order",
        "готовность": "readiness",
        "Детали фотографии": "Photo Details",
        "Скопировано!": "Copied!",
        "Копировать": "Copy",
        "Ошибка загрузки": "Upload Error",
        "ОК": "OK",
        "Ок": "Ok",
        "FTP Логи": "FTP Logs",
        "Offline": "Offline"
    ]
    
    private static let hyTranslations: [String: String] = [
        // Экран параметров системы
        "Параметры системы": "Համակարգի կարգավորումներ",
        "Интерфейс": "Ինտերֆեյս",
        "Интерфейс и Оформление": "Ինտերֆեյս և Տեսք",
        "Автозагрузка папки (Планировщик)": "Թղթապանակի ավտովերբեռնում (Պլանավորող)",
        "Параметры выгрузки и очередность": "Վերբեռնման պարամետրեր և հերթականություն",
        "Память и Очистка кэша": "Հիշողություն և Քեշի մաքրում",
        "Язык приложения": "Հավելվածի լեզու",
        "ОБЛАКО GOOGLE ФОТО": "GOOGLE ԼՈՒՍԱՆԿԱՐՆԵՐԻ ԱՄՊ",
        "Google Фото и Drive": "Google Լուսանկարներ և Drive",
        "Параметры Google Фото": "Google Լուսանկարների կարգավորումներ",
        "Подключить": "Միացնել",
        "Подключено к Google Фото": "Միացված է Google Լուսանկարներին",
        "Не подключено": "Միացված չէ",
        "Импорт видео и фото из архива Google Фото": "Վիդեոների և լուսանկարների ներմուծում Google Լուսանկարների արխիվից",
        "Выход из Google Фото выполнен": "Ելքը Google Լուսանկարներից կատարված է",
        "Ваш Client ID из Google Cloud Console...": "Ձեր Client ID-ն Google Cloud Console-ից...",
        "Вставьте Client ID из Google Cloud Console...": "Տեղադրեք Client ID-ն Google Cloud Console-ից...",
        "Google OAuth Client ID": "Google OAuth Client ID",
        "Google OAuth Client ID (необязательно)": "Google OAuth Client ID (ըստ ցանկության)",
        "Используется для прямого доступа к API Google Фото и Drive.": "Օգտագործվում է Google Լուսանկարների և Drive-ի API-ին ուղիղ մուտքի համար:",
        "Интеллектуальный Помощник": "Խելացի Օգնական",
        "Настройте ИИ для мгновенной индексации ваших кадров. Генерация коммерческих названий и SEO-тегов.": "Կարգավորեք ԱԻ-ն ձեր կադրերի ակնթարթային ինդեքսավորման համար: Կոմերցիոն անվանումների և SEO-թեգերի գեներացիա:",
        "ИИ провайдеры": "ԱԻ Մատակարարներ",
        "Введите личный токен аутентификации API": "Մուտքագրեք անձնական API վավերացման թոքենը",
        "Вставьте ключ API...": "Տեղադրեք API բանալին...",
        "Промпт для ИИ-анализа": "ԱԻ վերլուծության հրահանգ",
        "Подключение Google Фото": "Google Լուսանկարների միացում",
        "Выбирайте исходные видео и фото прямо из вашего облачного архива для публикации на стоках.": "Ընտրեք բնօրինակ վիդեոներ և լուսանկարներ անմիջապես ամպային արխիվից՝ ստոկերում հրապարակելու համար:",
        "Открытие окна авторизации Google...": "Google վավերացման պատուհանի բացում...",
        "Пожалуйста, введите ваш Google Client ID в параметрах системы.": "Խնդրում ենք մուտքագրել ձեր Google Client ID-ն համակարգի կարգավորումներում:",
        "Успешная авторизация в Google": "Հաջող վավերացում Google-ում",
        "Отключено от Google Фото": "Անջատված է Google Լուսանկարներից",
        "Настройка Google Фото": "Google Լուսանկարների կարգավորում",
        "Пошаговое руководство по получению Client ID": "Քայլ առ քայլ ուղեցույց Client ID ստանալու համար",
        "Создайте проект в Google Cloud": "Ստեղծեք նախագիծ Google Cloud-ում",
        "Перейдите в консоль разработчика Google Cloud и создайте новый бесплатный проект (например, SmartStock).": "Անցեք Google Cloud մշակողի կոնսոլ և ստեղծեք նոր անվճար նախագիծ (օրինակ՝ SmartStock):",
        "Включите Photos Library API": "Միացրեք Photos Library API-ն",
        "В разделе «APIs & Services» → «Library» найдите «Photos Library API» (а также «Google Drive API») и нажмите кнопку «Enable» (Включить).": "«APIs & Services» → «Library» բաժնում գտեք «Photos Library API»-ն (և «Google Drive API»-ն) ու սեղմեք «Enable» (Միացնել):",
        "Настройте OAuth Consent Screen": "Կարգավորեք OAuth Consent Screen-ը",
        "В разделе «OAuth consent screen» выберите тип «External» (Внешний), укажите имя приложения и ваш email. В блоке «Test users» добавьте свой Gmail-адрес.": "«OAuth consent screen» բաժնում ընտրեք «External» տեսակը, նշեք հավելվածի անվանումը և ձեր էլ. հասցեն: «Test users» դաշտում ավելացրեք ձեր Gmail հասցեն:",
        "Создайте OAuth Client ID": "Ստեղծեք OAuth Client ID",
        "В разделе «Credentials» нажмите «+ Create Credentials» → «OAuth client ID». Выберите тип приложения «iOS» (Bundle ID: com.samvel.smartstock.SmartStock) или «Web application».": "«Credentials» բաժնում սեղմեք «+ Create Credentials» → «OAuth client ID»: Ընտրեք հավելվածի տեսակը՝ «iOS» (Bundle ID: com.samvel.smartstock.SmartStock) կամ «Web application»:",
        "Вставьте Client ID в приложение": "Տեղադրեք Client ID-ն հավելվածում",
        "Скопируйте полученный идентификатор (вида xxxx.apps.googleusercontent.com) и вставьте в поле Client ID в приложении.": "Պատճենեք ստացված նույնացուցիչը (տեսքը՝ xxxx.apps.googleusercontent.com) և տեղադրեք հավելվածի Client ID դաշտում:",
        "Открыть Google Cloud Console": "Բացել Google Cloud Console-ը",
        "Инструкция Google Фото": "Google Լուսանկարների ուղեցույց",
        "Как получить API-ключ": "Ինչպես ստանալ API բանալի",
        "Бесплатно": "Անվճար",
        "Рекомендуемый провайдер: самый быстрый и бесплатный доступ.": "Առաջարկվող մատակարար՝ ամենաարագ և անվճար մուտք:",
        "Откройте Google AI Studio": "Բացեք Google AI Studio-ն",
        "Перейдите на официальный портал Google AI Studio (aistudio.google.com).": "Անցեք Google AI Studio պաշտոնական պորտալ (aistudio.google.com):",
        "Войдите с Google-аккаунтом": "Մուտք գործեք Google հաշվով",
        "Используйте ваш обычный личный аккаунт Google для входа в сервис.": "Ծառայություն մուտք գործելու համար օգտագործեք ձեր անձնական Google հաշիվը:",
        "Нажмите «Create API key»": "Սեղմեք «Create API key»",
        "Нажмите синюю кнопку «Create API key» (Создать ключ API) и выберите или создайте проект.": "Սեղմեք կապույտ «Create API key» կոճակը և ընտրեք կամ ստեղծեք նախագիծ:",
        "Скопируйте и вставьте ключ": "Պատճենեք և տեղադրեք բանալին",
        "Скопируйте сгенерированный ключ (начинается на «AIzaSy...») и вставьте в приложении в поле Gemini.": "Պատճենեք գեներացված բանալին (սկսվում է «AIzaSy...»-ով) և տեղադրեք հավելվածի Gemini դաշտում:",
        "Получить ключ в Google AI Studio": "Ստանալ բանալի Google AI Studio-ում",
        "Высокое качество индексации через модели GPT-4o и GPT-4o-mini.": "Ինդեքսավորման բարձր որակ GPT-4o և GPT-4o-mini մոդելների միջոցով:",
        "Откройте OpenAI Platform": "Բացեք OpenAI Platform-ը",
        "Перейдите на страницу ключей API (platform.openai.com/api-keys).": "Անցեք API բանալիների էջ (platform.openai.com/api-keys):",
        "Создайте новый секретный ключ": "Ստեղծեք նոր գաղտնի բանալի",
        "Нажмите кнопку «+ Create new secret key», укажите название и сохраните ключ.": "Սեղմեք «+ Create new secret key» կոճակը, նշեք անվանումը և պահպանեք բանալին:",
        "Вставьте ключ в приложение": "Տեղադրեք բանալին հավելվածում",
        "Скопируйте ключ (начинается на «sk-...») и вставьте в поле OpenAI в настройках ИИ.": "Պատճենեք բանալին (սկսվում է «sk-...»-ով) և տեղադրեք հավելվածի OpenAI դաշտում:",
        "Открыть OpenAI API Keys": "Բացել OpenAI API Keys-ը",
        "Глубокое понимание коммерческой эстетики через Claude 3.5 Sonnet.": "Կոմերցիոն էսթետիկայի խորը ըմբռնում Claude 3.5 Sonnet-ի միջոցով:",
        "Откройте Anthropic Console": "Բացեք Anthropic Console-ը",
        "Перейдите на страницу ключей (console.anthropic.com/settings/keys).": "Անցեք բանալիների էջ (console.anthropic.com/settings/keys):",
        "Создайте API-ключ": "Ստեղծեք API բանալի",
        "Нажмите «Create Key», задайте имя и скопируйте сформированный токен.": "Սեղմեք «Create Key», տվեք անուն և պատճենեք գեներացված թոքենը:",
        "Скопируйте ключ (начинается на «sk-ant-...») и вставьте в поле Claude в настройках ИИ.": "Պատճենեք բանալին (սկսվում է «sk-ant-...»-ով) և տեղադրեք հավելվածի Claude դաշտում:",
        "Открыть Anthropic Console": "Բացել Anthropic Console-ը",
        "Импортировать в очередь": "Ներմուծել հերթ",
        "Медиафайлов не найдено. Проверьте, включен ли Photos/Drive API в Google Cloud.": "Մեդիաֆայլեր չեն գտնվել: Ստուգեք՝ արդյոք Photos/Drive API-ն միացված է Google Cloud-ում:",
        "Подписка": "Բաժանորդագրություն",
        "Связь с App Store...": "Կապ App Store-ի հետ...",
        "Восстановить": "Վերականգնել",
        "Максимум продаж на стоках": "Առավելագույն վաճառքներ ստոկերում",
        "Автоматизируйте рутину и отправляйте сотни фото и видео на 10+ стоков в один клик.": "Ավտոմատացրեք առօրյան և ուղարկեք հարյուրավոր նկարներ ու վիդեոներ 10+ ստոկեր մեկ սեղմումով:",
        "Безлимитный ИИ-анализ кадра": "Անսահմանափակ ԱԻ վերլուծություն",
        "Генерация коммерческих названий, описаний и до 50 тегов через Gemini 2.5, GPT-4o, Claude": "Կոմերցիոն անվանումների, նկարագրությունների և մինչև 50 թեգերի գեներացիա Gemini 2.5, GPT-4o, Claude-ով",
        "Выгрузка на все 10+ стоков сразу": "Միաժամանակյա վերբեռնում 10+ ստոկեր",
        "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime и др.": "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime և այլն:",
        "Безлимитная очередь файлов": "Ֆայլերի անսահմանափակ հերթ",
        "Пакетная обработка и загрузка сотен фото и 4K/8K видео без пауз и ограничений": "Հարյուրավոր լուսանկարների և 4K/8K վիդեոների խմբային մշակում և վերբեռնում առանց սահմանափակումների",
        "Google Фото и Google Диск": "Google Լուսանկարներ և Google Drive",
        "Неограниченный импорт исходных медиафайлов прямо из облака": "Մեդիաֆայլերի անսահմանափակ ներմուծում անմիջապես ամպից",
        "Экспорт CSV и метаданных": "CSV և մետատվյալների արտահանում",
        "Мгновенное создание таблиц метаданных для любых агентств": "Մետատվյալների աղյուսակների ակնթարթային ստեղծում ցանկացած գործակալության համար",
        "ВЫГОДА 50% • 3 ДНЯ БЕСПЛАТНО": "ՇԱՀԱՎԵՏ 50% • 3 ՕՐ ԱՆՎՃԱՐ",
        "Годовая подписка": "Տարեկան բաժանորդագրություն",
        "Всего ~249 ₽ в месяц. Списание после 3-дневного триала.": "Տարեկան վճարում 3-օրյա անվճար փորձաշրջանից հետո:",
        "Месячная подписка": "Ամսական բաժանորդագրություն",
        "Ежемесячный доступ со всеми обновлениями.": "Ամսական մուտք բոլոր թարմացումներով:",
        "НАВСЕГДА": "ԸՆԴՄԻՇՏ",
        "Пожизненный PRO": "Ցմահ PRO",
        "Один платёж раз и навсегда. Без подписок.": "Մեկ վճարում ընդմիշտ: Առանց բաժանորդագրությունների:",
        "Попробовать 3 дня бесплатно": "Փորձել 3 օր անվճար",
        "Продолжить с SmartStock PRO": "Շարունակել SmartStock PRO-ով",
        "Подписка продлевается автоматически, пока не будет отменена в настройках Apple ID не менее чем за 24 часа до окончания текущего периода.": "Բաժանորդագրությունն ավտոմատ երկարաձգվում է, քանի դեռ այն չի չեղարկվել Apple ID-ի կարգավորումներում ընթացիկ ժամանակաշրջանի ավարտից առնվազն 24 ժամ առաջ:",
        "Условия использования (EULA)": "Օգտագործման պայմաններ (EULA)",
        "Политика конфиденциальности": "Գաղտնիության քաղաքականություն",
        "Поздравляем! SmartStock PRO успешно активирован! 🎉": "Շնորհավորում ենք: SmartStock PRO-ն հաջողությամբ ակտիվացված է: 🎉",
        "Не удалось подключиться к App Store. Пожалуйста, проверьте интернет-соединение.": "Չհաջողվեց միանալ App Store-ին: Խնդրում ենք ստուգել ինտերնետ կապը:",
        "Ваши покупки успешно восстановлены! Доступ к SmartStock PRO открыт.": "Ձեր գնումները հաջողությամբ վերականգնվել են: SmartStock PRO մուտքը բաց է:",
        "Активных подписок не найдено. Если вы совершали покупку, убедитесь, что вошли под нужным Apple ID.": "Ակտիվ բաժանորդագրություններ չեն գտնվել: Եթե նախկինում գնել եք, համոզվեք, որ մուտք եք գործել ճիշտ Apple ID-ով:",
        "АКТИВЕН": "ԱԿՏԻՎ Է",
        "Все премиум-функции и безлимитный ИИ активны": "Բոլոր պրեմիում ֆունկցիաները և անսահմանափակ ԱԻ-ն ակտիվ են",
        "Перейти на SmartStock PRO": "Անցնել SmartStock PRO-ի",
        "Безлимитный ИИ, 10+ стоков и автозагрузка": "Անսահմանափակ ԱԻ, 10+ ստոկեր և ավտովերբեռնում",
        "В бесплатной версии доступно до 2 стоков. Перейдите на PRO для одновременной выгрузки на все стоки!": "Անվճար տարբերակում հասանելի է մինչև 2 ստոկ: Անցեք PRO-ի՝ բոլոր ստոկեր միաժամանակ վերբեռնելու համար!",
        "Динамика загрузок": "Վերբեռնումների դինամիկա",
        "Сводка активности": "Գործունեության ամփոփագիր",
        "История выгрузок": "Վերբեռնումների պատմություն",
        "По стокам": "Ըստ ստոկերի",
        "подключено": "միացված է",
        "История пуста": "Պատմությունը դատարկ է",
        "Очистить историю": "Մաքրել պատմությունը",
        "Очистить историю?": "Մաքրե՞լ պատմությունը:",
        "Вся история загрузок будет удалена. Это действие нельзя отменить.": "Վերբեռնումների ամբողջ պատմությունը կջնջվի: Այս գործողությունը հնարավոր չէ չեղարկել:",
        "Очистить": "Մաքրել",
        "Недавние": "Վերջինները",
        "Порядок": "Կարգ",
        "Выбрать": "Ընտրել",
        "Поиск фото, альбомов...": "Լուսանկարների, ալբոմների որոնում...",
        "Статистика очереди": "Հերթի վիճակագրություն",
        "Всего": "Ընդհանուր",
        "всего": "ընդհանուր",
        "загрузок": "վերբեռնում",
        "готовность": "պատրաստվածություն",
        "Покупки": "Գնումներ",
        "Синхронизация": "Սինխրոնացում",
        "Активно": "Ակտիվ",
        "Нет данных": "Տվյալներ չկան",
        "Демо": "Դեմո",
        "Все стоки": "Բոլոր ստոկերը",
        "Загрузки": "Վերբեռնումներ",
        "Успешно": "Հաջողվել է",
        "Ошибок": "Սխալներ",
        "Ошибки": "Սխալներ",
        "Фото": "Լուսանկարներ",
        "Видео": "Վիդեոներ",
        "Ок": "Լավ",
        "Язык интерфейса": "Ինտերֆեյսի լեզու",
        "Тема оформления": "Թեմա",
        "Темная": "Մութ",
        "Светлая": "Բաց",
        "Системная": "Համակարգային",
        "Предел частоты кадров": "Կադրերի հաճախականություն",
        "Планировщик": "Պլանավորող",
        "Фоновый планировщик выгрузки": "Վերբեռնման ֆոնային պլանավորող",
        "При активации планировщика система будет проверять новые фото и отправлять их в фоновом режиме.": "Պլանավորողն ակտիվացնելիս համակարգը կստուգի նոր լուսանկարները և կուղարկի դրանք ֆոնային ռեժիմում։",
        "Папка для импорта": "Ներմուծման թղթապանակ",
        "Выбрать...": "Ընտրել...",
        "Интервал проверки": "Ստուգման միջակայք",
        "Каждые": "Յուրաքանչյուր",
        "Еще не запускался": "Դեռ չի գործարկվել",
        "Запуск проверки...": "Ստուգման գործարկում...",
        "Запустить проверку сейчас": "Գործարկել ստուգումը հիմա",
        "При активации планировщика система будет проверять новые фото в выбранной папке и отправлять их в фоновом режиме.": "Պլանավորողն ակտիվացնելիս համակարգը կստուգի նոր լուսանկարները ընտրված թղթապանակում և կուղարկի դրանք ֆոնային ռեժիմում։",
        "Проверка папки завершена!": "Թղթապանակի ստուգումն ավարտվեց։",
        "Не удалось получить доступ к папке": "Չհաջողվեց մուտք գործել թղթապանակ",
        "Папка успешно выбрана: ": "Թղթապանակը հաջողությամբ ընտրվեց՝ ",
        "Ошибка сохранения папки: ": "Թղթապանակի պահպանման սխալ՝ ",
        "Планировщик выгрузки": "Վերբեռնման պլանավորող",
        "Фоновая обработка завершена. Новых файлов загружено: ": "Ֆոնային մշակումն ավարտվեց։ Նոր վերբեռնված ֆայլեր՝ ",
        "час": "ժամ",
        "часа": "ժամ",
        "часов": "ժամ",
        "Автоматический Апскейл": "Ավտոմատ Ափսքեյլ",
        "Включить авто-апскейл": "Միացնել ավտո-ափսքեյլը",
        "Порог срабатывания": "Գործարկման շեմ",
        "Коэффициент (масштаб)": "Գործակից (մասշտաբ)",
        "Параметры выгрузки": "Վերբեռնման կարգավորումներ",
        "Потоки параллельной загрузки": "Զուգահեռ վերբեռնման հոսքեր",
        "Автоповтор при сбоях": "Ավտո-կրկնում սխալների դեպքում",
        "Сжатие JPEG перед загрузкой": "JPEG սեղմում վերբեռնումից առաջ",
        "Системные уведомления": "Համակարգային ծանուցումներ",
        "Локальный ПК-сервер": "Լոկալ ՊԿ-սերվեր",
        "Загрузка через ПК-сервер": "Վերբեռնում ՊԿ-սերվերի միջոցով",
        "Адрес сервера (IP:Порт)": "Սերվերի հասցե (IP:Port)",
        "Позволяет отправлять фото через программу на вашем компьютере. Полезно, если на телефоне блокируется FTPS к Shutterstock.": "Թույլ է տալիս ուղարկել լուսանկարներ համակարգչի ծրագրով: Օգտակար է, եթե հեռախոսում արգելափակվում է FTPS-ը դեպի Shutterstock:",
        "Облачная синхронизация": "Ամպային սինխրոնացում",
        "Синхронизация профиля активна": "Պրոֆիլի սինխրոնացումն ակտիվ է",
        "Выйти": "Դուրս գալ",
        "Войдите в аккаунт, чтобы синхронизировать ваши настройки стоков и ключи API в облаке.": "Մուտք գործեք հաշիվ՝ ամպում ստոկերի կարգավորումները և API բանալիները սինխրոնացնելու համար։",
        "Вход с Google": "Մուտք Google-ով",
        "Сохранить все настройки": "Պահպանել բոլոր կարգավորումները",
        
        // Экран стоков
        "Интегрированные фотостоки": "Ինտեգրված ֆոտոստոկեր",
        "Настройки стоков": "Ստոկերի կարգավորումներ",
        "Проверка соединения...": "Միացման ստուգում...",
        "Настроен": "Կարգավորված է",
        "Нужна настройка": "Պահանջվում է կարգավորում",
        "Параметры SFTP / FTP для": "SFTP / FTP կարգավորումներ սրա համար՝",
        "Активен": "Ակտիվ է",
        "Имя пользователя (логин)": "Օգտանուն (լոգին)",
        "Пароль": "Գաղտնաբառ",
        "Дополнительные параметры сервера": "Սերվերի լրացուցիչ կարգավորումներ",
        "Имя хоста (сервер)": "Հոսթի անուն (սերվեր)",
        "Проверить соединение": "Ստուգել միացումը",
        "Проверка...": "Ստուգում...",
        "Готово": "Պատրաստ է",
        "Подключение": "Միացում",
        "Пожалуйста, введите логин и пароль.": "Խնդրում ենք մուտքագրել մուտքանունը և գաղտնաբառը:",
        
        // Вкладки таб-бара
        "Очередь": "Հերթ",
        "ИИ-Ассистент": "ԱԻ-Օգնական",
        "Стоки": "Ստոկեր",
        "Параметры": "Կարգավորումներ",
        "Галерея": "Պատկերասրահ",
        "ИИ": "ԱԻ Մոդելներ",
        "Статистика": "Վիճակագրություն",
        "Агентства": "Գործակալություններ",
        "Настройки": "Կարգավորումներ",
        "Общий баланс": "Ընդհանուր հաշվեկշիռ",
        "За последние 30 дней": "Վերջին 30 օրվա ընթացքում",
        "Ожидает подтверждения": "Սպասում է հաստատման",
        "История доходов": "Եկամուտների պատմություն",
        "Эффективность агентств": "Գործակալությունների արդյունավետությունը",
        "Показать все": "Տեսնել բոլորը",
        "Проверено": "Ստուգված է",
        "В ожидании": "Սպասման մեջ",
        "На удержании": "Պահման մեջ",
        "Синхронизация: ": "Սինխրոնացում՝ ",
        "2 ч. назад": "2ժ առաջ",
        "5 ч. назад": "5ժ առաջ",
        "12 ч. назад": "12ժ առաջ",
        "1 д. назад": "1օր առաջ",
        "Вошли через Google или Apple?": "Մուտք եք գործել Google-ո՞վ թե Apple-ով",
        "Важно для Google / Apple": "Կարևոր է Google / Apple-ի համար",
        "Если вы регистрировались на фотостоках через аккаунт Google или Apple, прямой вход по паролю этих сервисов не поддерживается для FTP/SFTP загрузки (это техническое ограничение самих стоков).": "Եթե գրանցվել եք ֆոտոստոկերում Google կամ Apple հաշվով, այս ծառայությունների գաղտնաբառով ուղիղ մուտքը չի աջակցվում FTP/SFTP վերբեռնման համար:",
        "Для выгрузки из приложения вам необходимо использовать специальный FTP-пароль, сгенерированный в личном кабинете автора.": "Հավելվածից վերբեռնելու համար անհրաժեշտ է օգտագործել հեղինակի անձնական կաբինետում գեներացված հատուկ FTP-գաղտնաբառ:",
        "Инструкция для Adobe Stock": "Հրահանգ Adobe Stock-ի համար",
        "1. Войдите в личный кабинет автора на contributor.adobestock.com.": "1. Մուտք գործեք հեղինակի անձնական կաբինետ contributor.adobestock.com կայքում:",
        "2. Перейдите в 'Настройки учетной записи' (нажав на свой профиль в правом верхнем углу).": "2. Անցեք «Հաշվի կարգավորումներ» բաժին (սեղմելով ձեր պրոֆիլին վերևի աջ անկյունում):",
        "3. В подразделе 'Настройки FTP' вы увидите ваш персональный логин (ID) и сгенерированный FTP-пароль.": "3. «FTP կարգավորումներ» ենթաբաժնում դուք կտեսնեք ձեր անձնական օգտանունը (ID) և գեներացված FTP-գաղտնաբառը:",
        "4. Вставьте эти данные в настройки Adobe Stock в приложении.": "4. Տեղադրեք այս տվյալները հավելվածում Adobe Stock-ի կարգավորումներում:",
        "Открыть Adobe Stock Contributor": "Բացել Adobe Stock Contributor",
        "Инструкция для Shutterstock": "Հրահանգ Shutterstock-ի համար",
        "1. Войдите в кабинет автора на submit.shutterstock.com.": "1. Մուտք գործեք հեղինակի կաբինետ submit.shutterstock.com կայքում:",
        "2. Перейдите в настройки аккаунта 'Account Settings'.": "2. Անցեք հաշվի կարգավորումներ «Account Settings»:",
        "3. Найдите раздел FTP и скопируйте предоставленные учетные данные (обычно логином является ваш email).": "3. Գտեք FTP բաժինը և պատճենեք տրամադրված տվյալները (սովորաբար մուտքանունը ձեր էլ. հասցեն է):",
        "4. Введите их в настройки Shutterstock в приложении.": "4. Մուտքագրեք դրանք հավելվածում Shutterstock-ի կարգավորումներում:",
        "Открыть submit.shutterstock.com": "Բացել submit.shutterstock.com",
        "Вход через Google / Apple": "Մուտք Google / Apple-ով",
        
        // Экран очереди загрузки
        "Очередь выгрузки": "Վերբեռնման հերթ",
        "Готовы к загрузке": "Պատրաստ է վերբեռնման",
        "Загружено": "Վերբեռնված է",
        "В очереди": "Հերթում",
        "Ошибки": "Սխալներ",
        "Добавить фото": "Ավելացնել լուսանկար",
        "Загрузить все": "Վերբեռնել բոլորը",
        "ИИ Анализ": "ԱԻ Վերլուծություն",
        "Удалить": "Ջնջել",
        "Редактировать": "Խմբագրել",
        "Настройки стоков для фото": "Ստոկերի կարգավորումներ լուսանկարի համար",
        "Файл": "Ֆայլ",
        "Размер": "Չափ",
        "Статус": "Կարգավիճակ",
        "Загрузить новый контент": "Վերբեռնել նոր բովանդակություն",
        "Нажмите для выбора или перетащите": "Հպեք ընտրելու համար կամ քաշեք այստեղ",
        "Поиск фото, альбомов...": "Փնտրել նկարներ, ալբոմներ...",
        "Недавние": "Վերջինները",
        "Выбрать": "Ընտրել",
        "Очередь пуста": "Հերթը դատարկ է",
        "Выберите снимки, чтобы запустить ИИ-подбор метаданных и отправить их на микростоки.": "Ընտրեք լուսանկարներ ԱԻ метаտվյալների ընտրությունը գործարկելու և միկրոստոկեր ուղարկելու համար։",
        "Запустить ИИ-анализ": "Գործարկել ԱԻ վերլուծություն",
        "Выгрузить на стоки": "Վերբեռնել ստոկեր",
        "ИИ для выбранных": "ԱԻ ընտրվածների համար",
        "Отправить выбр.": "Ուղարկել ընտրվածները",
        "Заполнить все ИИ": "Լրացնել բոլորը ԱԻ-ով",
        "Отправить": "Ուղարկել",
        "Порядок очереди": "Հերթի կարգը",
        "Ключевые слова отсутствуют. Запустите ИИ-анализ.": "Բանալի բառերը բացակայում են։ Գործարկեք ԱԻ վերլուծություն։",
        "Отправить на стоки": "Ուղարկել ստոկեր",
        "Заполнить ИИ": "Լրացնել ԱԻ-ով",
        "Выбрать стоки...": "Ընտրել ստոկեր...",
        "Удалить из очереди": "Հեռացնել հերթից",
        "Подробнее": "Մանրամասն",
        "Скопировать": "Պատճենել",
        "Закрыть": "Փակել",
        
        // ИИ-Ассистент
        "Интеллектуальный ассистент": "Ինտելեկտուալ օգնական",
        "Интеллектуальный Помощник": "Ինտելեկտուալ Օգնական",
        "Генерация ключевых слов и описаний с помощью ИИ": "Բանալի բառերի և նկարագրությունների ստեղծում ԱԻ-ի միջոցով",
        "Настройте ИИ для мгновенной индексации ваших кадров. Генерация коммерческих названий и SEO-тегов.": "Կարգավորեք ԱԻ-ն ձեր կադրերի ակնթարթային ինդեքսավորման համար։ Կոմերցիոն վերնագրերի և SEO-թեգերի ստեղծում։",
        "ИИ провайдеры": "ԱԻ Մատակարարներ",
        "Параметры подключения": "Միացման Կարգավորումներ",
        "Введите личный токен аутентификации API": "Մուտքագրեք API նույնականացման ձեր անձնական Թոքենը",
        "Вставьте ключ API...": "Տեղադրեք API բանալին...",
        "Промпт для ИИ-анализа": "Հրահանգ ԱԻ վերլուծության համար",
        "Промпт определяет формат возвращаемого JSON-файла с заголовком и ключевыми словами.": "Հրահանգը սահմանում է վերադարձվող JSON ֆայլի ձևաչափը վերնագրով և բանալի բառերով։",
        "Анализ изображения": "Պատկերի վերլուծություն",
        "Результаты анализа": "Վերլուծության արդյունքներ",
        "Название": "Վերնագիր",
        "Описание": "Նկարագրություն",
        "Ключевые слова": "Բանալի բառեր",
        "Категории": "Կատեգորիաներ",
        "Скопировать все": "Պատճենել ամբողջը",
        "Применить к фото": "Կիրառել լուսանկարի վրա",
        "Стандартный": "Ստանդարտ",
        "Коммерческий": "Կոմերցիոն",
        "Репортажный": "Ռեպորտաժային",
        "Креативный": "Ստեղծագործական",
        "SEO-Максимум": "SEO-Առավելագույն",
        "Мини": "Մինի",
        "Не настроен": "Կարգավորված չէ",
        "Проверка ключа": "Բանալու ստուգում",
        "Пожалуйста, введите API-ключ перед проверкой.": "Խնդրում ենք մուտքագրել API բանալին ստուգումից առաջ:",
        
        // Экран редактирования метаданных
        "Метаданные": "Մետատվյալներ",
        "Заголовок": "Վերնագիր",
        "Заново": "Կրկին",
        "Заголовок фото": "Լուսանկարի վերնագիր",
        "Добавить слово": "Ավելացնել բառ",
        "Добавить": "Ավելացնել",
        "Категории (Макс. 2)": "Կատեգորիաներ (Առավ. 2)",
        "Лимит достигнут": "Սահմանաչափը լրացված է",
        "Категории не выбраны. Выберите до 2 категорий.": "Կատեգորիաներ ընտրված չեն։ Ընտրեք մինչև 2 կատեգորիա։",
        "Сохранить изменения": "Պահպանել փոփոխությունները",
        
        // Экран статистики
        "Все стоки": "Բոլոր ստոկերը",
        "Метрики": "Մետրիկաներ",
        "Загрузки": "Վերբեռնումներ",
        "Успешно": "Հաջողված",
        "Покупки": "Գնումներ",
        "Ошибок": "Սխալներ",
        "Синхронизация": "Սինխրոնացում",
        "Динамика загрузок": "Վերբեռնումների դինամիկա",
        "Демо": "Դեմո",
        "Активно": "Ակտիվ է",
        "Нет данных": "Տվյալներ չկան",
        "История загрузок": "Վերբեռնումների պատմություն",
        "записей": "գրանցումներ",
        "История пуста": "Պատմությունը դատարկ է",
        "Очистить историю": "Մաքրել պատմությունը",
        "Очистить": "Մաքրել",
        "Вся история загрузок будет удалена. Это действие нельзя отменить.": "Վերբեռնումների ամբողջ պատմությունը կջնջվի։ Այս գործողությունը հնարավոր չէ չեղարկել։",
        "По стокам": "Ըստ ստոկերի",
        "подключено": "միացված է",
        "Нет загрузок": "Վերբեռնումներ չկան",
        "Нет подключённых стоков": "Միացված ստոկեր չկան",
        "Перейдите в раздел «Агентства» и настройте учётные данные для Shutterstock, Adobe Stock или других стоков — статистика загрузок появится здесь автоматически.": "Անցեք «Գործակալություններ» բաժին և կարգավորեք Shutterstock-ի, Adobe Stock-ի կամ այլ ստոկերի տվյալները — վերբեռնումների վիճակագրությունը ավտոմատ կհայտնվի այստեղ։",
        "Перейти в настройки агентств →": "Անցնել գործակալությունների կարգավորումներին →",
        
        // Новые переводы для настроек
        "Меньше 4 МБ (Рекомендуется)": "4 ՄԲ-ից պակաս (Խորհուրդ է տրվում)",
        "Меньше 2 МБ": "2 ՄԲ-ից պակաս",
        "Меньше 8 МБ": "8 ՄԲ-ից պակաս",
        "Увеличение 2x (Бикубическое)": "Մեծացում 2x (Բիկուբիկ)",
        "Увеличение 4x (Нейросеть)": "Մեծացում 4x (Նեյրոցանց)",
        "120 FPS (Ультра-плавность)": "120 FPS (Գերսահուն)",
        "60 FPS (Стандартный)": "60 FPS (Ստանդարտ)",
        "30 FPS (Энергосбережение)": "30 FPS (Էներգախնայողություն)",
        "Русский": "Русский",
        "English": "English",
        "Настройки сохранены!": "Կարգավորումները պահպանված են։",
        "Настройки успешно сохранены!": "Կարգավորումները հաջողությամբ պահպանվեցին։",
        "Успешный вход через Apple!": "Հաջող մուտք Apple-ով",
        "Успешный вход через Google!": "Հաջող մուտք Google-ով",
        "Частота кадров: ": "Կադրերի հաճախականություն՝ ",
        " — применится при запуске": " — կկիրառվի վերագործարկելիս",
        "Параллельные потоки: ": "Զուգահեռ հոսքեր՝ ",
        " — применится при следующей загрузке": " — կկիրառվի հաջորդ վերբեռնման ժամանակ",
        "Авто-апскейл включён — работает при добавлении фото": "Ավտոմատ ափսքեյլը միացված է — աշխատում է լուսանկար ավելացնելիս",
        "Авто-апскейл отключён": "Ավտոմատ ափսքեյլն անջատված է",
        "Язык изменён на Русский": "Լեզուն փոխվեց Ռուսերենի",
        "Language changed to English": "Language changed to English",
        "поток": "հոսք",
        "потока": "հոսք",
        "потоков": "հոսք",
        "Авторизация...": "Մուտքի հաստատում...",
        
        // Экран настроек стоков
        "Успешное соединение с сервером": "Հաջող միացում սերվերին",
        "Ошибка соединения с": "Միացման սխալ սրա հետ՝",
        "Внимание: Данный сток требует SFTP. Plain FTP-соединение для него может быть недоступно.": "Ուշադրություն. Այս ստոկը պահանջում է SFTP: Սովորական FTP միացումը կարող է անհասանելի լինել:",
        
        // Вход и справка
        "Вход через": "Մուտք",
        "Введите вашу электронную почту для синхронизации аккаунта.": "Մուտքագրեք ձեր էլ. հասցեն հաշվի սինխրոնացման համար։",
        "Адрес электронной почты": "Էլ. փոստի հասցե",
        "Продолжить": "Շարունակել",
        "Безопасное соединение по стандарту OAuth 2.0": "Ապահով միացում OAuth 2.0 ստանդարտով",
        "Отмена": "Չեղարկել",
        "Инструкция по настройке FTP для": "FTP կարգավորման հրահանգներ սրա համար՝",
        "Из буфера": "Սեղմատախտակից",
        "Сканировать": "Սկանավորել",
        "Импортировать": "Ներմուծել",
        "Обнаружены данные для настройки": "Հայտնաբերվել են կարգավորման տվյալներ սրա համար՝",
        
        // Новые переводы для Очереди
        "Ошибка: Нет активных стоков или не введены логин/пароль!": "Սխալ. Ակվիտ ստոկեր չկան կամ մուտքանունը/գաղտնաբառը լրացված չեն:",
        "Загрузка файла": "Ֆայլի վերբեռնում",
        "Нет файлов, готовых к отправке.": "Ուղարկման պատրաստ ֆայլեր չկան:",
        "успешно загружен на стоки!": "հաջողությամբ վերբեռնվեց ստոկեր։",
        "Ошибка выгрузки": "Վերբեռնման սխալ",
        "успешно загружен!": "հաջողությամբ վերբեռնվեց։",
        "Ошибка:": "Սխալ՝",
        "Успешная выгрузка": "Հաջող վերբեռնում",
        "Нажмите на агентство ниже, чтобы зайти в личный кабинет через встроенный браузер.": "Հպվեք գործակալությանը ստորև՝ ներկառուցված բրաուզերով անձնական կաբինետ մուտք գործելու համար։",
        "ИИ АНАЛИЗ": "ԱԻ ՎԵՐԼՈՒԾՈՒԹՅՈՒՆ",
        "Анализируем...": "Վերլուծվում է...",
        "Ваш умный микростоковый менеджер": "Ձեր խելացի միկրոստոկային մենեջերը",
        "Вход в систему": "Մուտք",
        "Регистрация": "Գրանցում",
        "Email": "Էլ. հասցե",
        "Зарегистрироваться": "Գրանցվել",
        "Войти": "Մուտք գործել",
        "или": "կամ",
        "У вас нет аккаунта?": "Չունե՞ք հաշիվ",
        "Уже есть аккаунт?": "Արդեն ունե՞ք հաշիվ",
        "Введите ваш Email": "Մուտքագրեք ձեր էլ. հասցեն",
        "Введите ваш пароль": "Մուտքագրեք ձեր գաղտնաբառը",
        "Некорректный формат Email": "Էլ. հասցեի անվավեր ձևաչափ",
        "Пароль должен содержать не менее 6 символов": "Գաղտնաբառը պետք է պարունակի առնվազն 6 նիշ",
        "Мой аккаунт": "Իմ հաշիվը",
        "Выйти из аккаунта": "Դուրս գալ հաշվից",
        "Вы уверены, что хотите выйти из аккаунта?": "Համոզվա՞ծ եք, որ ցանկանում եք դուրս գալ հաշվից:",
        "Частота кадров изменена на ": "Կադրերի հաճախականությունը փոխվել է՝ ",
        "Статистика очереди": "Հերթի վիճակագրություն",
        "Всего": "Ընդամենը",
                "Автозагрузка папки (Планировщик)": "Թղթապանակի ավտո-վերբեռնում (Պլանավորող)",
        "Автоповтор при сбоях (3 попытки)": "Ավտո-կրկնում սխալների դեպքում (3 փորձ)",
        "Без названия": "Անանուն",
        "В ОЧЕРЕДИ": "ՀԵՐԹՈՒՄ",
        "Видеофайлы отправляются строго по очереди один за другим без перегрева процессора.": "Տեսանյութերը ուղարկվում են խիստ հերթականությամբ մեկը մյուսի հետևից:",
        "Войти через Помощник (авто-настройка)": "Մուտք Օգնականով (ավտո-կարգավորում)",
        "Выбирайте исходные видео и фото прямо из вашего облачного архива для публикации на стоках.": "Ընտրեք բնօրինակ տեսանյութերն ու լուսանկարները անմիջապես ամպային արխիվից:",
        "Высокий": "Բարձր",
        "ГОТОВ": "ՊԱՏՐԱՍՏ Է",
        "Демо-описание: Живописный закат солнца над горным хребтом.": "Դեմո-նկարագրություն՝ Տեսարժան մայրամուտ լեռնաշղթայի վրա։",
        "Драматичный закат в горах (Демо)": "Դրամատիկ մայրամուտ լեռներում (Դեմո)",
        "Загрузка видео по очереди (Строго 1 за 1)": "Տեսանյութերի հերթական վերբեռնում (Խիստ 1-ական)",
        "Загрузка видео по очереди включена": "Տեսանյութերի հերթական վերբեռնումը միացված է",
        "Загрузка видео по очереди отключена": "Տեսանյութերի հերթական վերբեռնումն անջատված է",
        "Загрузка медиафайлов...": "Մեդիաֆայլերի բեռնում...",
        "Загрузка фото по очереди": "Լուսանկարների հերթական վերբեռնում",
        "Загрузка фото по очереди включена": "Լուսանկարների հերթական վերբեռնումը միացված է",
        "Загрузка фото по очереди отключена": "Լուսանկարների հերթական վերբեռնումն անջատված է",
        "Загрузка...": "Բեռնում...",
        "Запущен ИИ-анализ для": "Գործարկվել է ԱԻ վերլուծություն սրա համար՝",
        "ИИ успешно заполнил метаданные для": "ԱԻ-ն հաջողությամբ լրացրեց մետատվյալները սրա համար՝",
        "Изменить": "Փոխել",
        "Интерфейс и Оформление": "Ինտերֆեյս և Ձևավորում",
        "Использовано диска:": "Օգտագործված սկավառակ՝",
        "КЛЮЧЕВЫЕ СЛОВА (Генерация ИИ)": "ԲԱՆԱԼԻ ԲԱՌԵՐ (ԱԻ Գեներացիա)",
        "Кэш скачанных медиафайлов очищен!": "Ներբեռնված մեդիաֆայլերի քեշը մաքրված է։",
        "Кэширование включено": "Քեշավորումը միացված է",
        "МЕТАДАННЫЕ": "ՄԵՏԱՏՎՅԱԼՆԵՐ",
        "Началась отправка": "Սկսվեց ուղարկումը՝",
        "Не выбрана": "Ընտրված չէ",
        "Не подключено": "Միացված չէ",
        "Нет новых файлов для ИИ-анализа.": "ԱԻ վերլուծության համար նոր ֆայլեր չկան։",
        "Обмен кода авторизации...": "Վավերացման կոդի փոխանակում...",
        "Описание отсутствует": "Նկարագրությունը բացակայում է",
        "Отправлено": "Ուղարկված է",
        "Очистить историю?": "Մաքրե՞լ պատմությունը։",
        "Очистка остаточного кэша": "Մնացորդային քեշի մաքրում",
        "Ошибка ИИ-анализа для": "ԱԻ վերլուծության սխալ սրա համար՝",
        "Ошибка сохранения папки:": "Թղթապանակի պահպանման սխալ՝",
        "ПРОГНОЗ ПОПУЛЯРНОСТИ (Рыночный анализ ИИ)": "ՊՈՊՈՒԼՅԱՐՈՒԹՅԱՆ ԿԱՆԽԱՏԵՍՈՒՄ (ԱԻ Շուկայական վերլուծություն)",
        "Память и Очистка кэша": "Հիշողություն և Քեշի մաքրում",
        "Папка для сканирования": "Սկանավորման թղթապանակ",
        "Папка успешно выбрана:": "Թղթապանակը հաջողությամբ ընտրվեց՝",
        "Параллельные потоки:": "Զուգահեռ հոսքեր՝",
        "Параметры выгрузки и очередность": "Վերբեռնման կարգավորումներ և հերթականություն",
        "Подготовка воспроизведения видео...": "Տեսանյութի նվագարկման պատրաստում...",
        "Подключено": "Միացված է",
        "Подключить": "Միացնել",
        "Позволяет отправлять фото через программу на вашем компьютере.": "Թույլ է տալիս ուղարկել լուսանկարներ համակարգչի ծրագրով:",
        "Поиск по файлам...": "Փնտրել ֆայլերում...",
        "Последний запуск": "Վերջին գործարկում",
        "Правовая информация и товарные знаки": "Իրավական տեղեկատվություն և ապրանքանիշեր",
        "Приложение работает как прямой проводник: файлы отправляются без дублирования на диск телефона.": "Հավելվածն աշխատում է որպես ուղիղ ուղղորդիչ՝ ֆայլերը ուղարկվում են առանց հեռախոսում դուբլիկատավորման։",
        "Проверка подключения к": "Միացման ստուգում դեպի՝",
        "Режим проводника (Прямая выгрузка без кэша)": "Ուղղորդիչի ռեժիմ (Ուղիղ վերբեռնում առանց քեշի)",
        "Режим проводника активен: 0 МБ кэша": "Ուղղորդիչի ռեժիմն ակտիվ է՝ 0 ՄԲ քեշ",
        "Сервер выгрузки:": "Վերբեռնման սերվեր՝",
        "Синхронизация:": "Սինխրոնացում՝",
        "Статус:": "Կարգավիճակ՝",
        "Учетные данные обнаружены": "Մուտքային տվյալները հայտնաբերված են",
        "Файлы на устройстве": "Ֆայլեր սարքում",
        "Файлы не найдены": "Ֆայլեր չեն գտնվել",
        "Фоновый авто-сканер": "Ֆոնային ավտո-սկաներ",
        "Фотографии будут отправляться строго последовательно по одной.": "Լուսանկարները կուղարկվեն խիստ հերթականությամբ մեկ առ մեկ։",
        "Язык приложения": "Հավելվածի լեզու",
        "всего": "ընդամենը",
        "загрузок": "վերբեռնումներ",
        "из": "-ից",
        "файлов...": "ֆայլեր...",
        "Фото": "Լուսանկարներ",
        "Видео": "Տեսանյութեր",
        "Порядок": "Կարգ",
        "готовность": "պատրաստվածություն",
        "Детали фотографии": "Լուսանկարի մանրամասներ",
        "Скопировано!": "Պատճենված է։",
        "Копировать": "Պատճենել",
        "Ошибка загрузки": "Վերբեռնման սխալ",
        "ОК": "OK",
        "Ок": "OK",
        "FTP Логи": "FTP Լոգեր",
        "Offline": "Անցանց"
    ]
    
    /// Потокобезопасный перевод строки с синхронизацией через NSLock
    static func translate(_ text: String, to lang: String) -> String {
        guard lang != "Русский" && !text.isEmpty else {
            return text
        }
        
        lock.lock()
        defer { lock.unlock() }
        
        let dict = (lang == "Հայերեն" || lang == "Armenian") ? hyTranslations : enTranslations
        
        // 1. Точное совпадение по словарю
        if let translation = dict[text] {
            return translation
        }
        
        // 2. Безопасная обработка префиксов для динамических шаблонов
        let dynamicPrefixes = [
            "Частота кадров: ",
            "Частота кадров изменена на ",
            "Параллельные потоки: ",
            "Язык изменён на ",
            "Файл ",
            "Началась отправка ",
            "Ошибка соединения с ",
            "Синхронизация: ",
            "Инструкция по настройке FTP для ",
            "Обнаружены данные для настройки ",
            "Вход через ",
            "Проверка подключения к "
        ]
        
        for prefix in dynamicPrefixes {
            if text.hasPrefix(prefix) {
                let translatedPrefix = dict[prefix] ?? prefix
                let remainder = String(text.dropFirst(prefix.count))
                let translatedRemainder = dict[remainder] ?? remainder
                return translatedPrefix + translatedRemainder
            }
        }
        
        return text
    }
}
