import Foundation

extension String {
    /// Потокобезопасное получение локализованной строки.
    /// Если язык — "Русский", возвращает исходную строку без обращения к словарям.
    var localized: String {
        guard let currentLang = UserDefaults.standard.string(forKey: "sys_language"),
              currentLang != "Русский" && !currentLang.isEmpty else {
            return self
        }
        return Localizer.translate(self, to: currentLang)
    }
}

struct Localizer {
    /// Рекурсивная блокировка для защиты обращения к словарям из любых потоков (Data Race & Deadlock Prevention)
    private static let lock = NSRecursiveLock()
    
    private static let enTranslations: [String: String] = [
        " — применится при запуске": " — will apply on restart",
        " — применится при следующей загрузке": " — will apply on next upload",
        "+5 бонусных фото начислены в вашу очередь": "+5 bonus photo slots added to your queue",
        "1 д. назад": "1d ago",
        "1. Войдите в кабинет автора на submit.shutterstock.com.": "1. Log in to the contributor dashboard at submit.shutterstock.com.",
        "1. Войдите в личный кабинет автора на contributor.adobestock.com.": "1. Log in to the contributor dashboard at contributor.adobestock.com.",
        "100K+ Загрузок": "100K+ Downloads",
        "12 ч. назад": "12h ago",
        "120 FPS (Ультра-плавность)": "120 FPS (Ultra-smooth)",
        "2 ч. назад": "2h ago",
        "2. Перейдите в 'Настройки учетной записи' (нажав на свой профиль в правом верхнем углу).": "2. Go to 'Account Settings' (by clicking on your profile in the top-right corner).",
        "2. Перейдите в настройки аккаунта 'Account Settings'.": "2. Go to 'Account Settings'.",
        "3. В подразделе 'Настройки FTP' вы увидите ваш персональный логин (ID) и сгенерированный FTP-пароль.": "3. Under the 'FTP Settings' sub-section, you will see your personal username (ID) and generated FTP password.",
        "3. Найдите раздел FTP и скопируйте предоставленные учетные данные (обычно логином является ваш email).": "3. Locate the FTP section and copy the provided credentials (typically your email is the username).",
        "30 FPS (Энергосбережение)": "30 FPS (Power Saving)",
        "4. Введите их в настройки Shutterstock в приложении.": "4. Enter them into the Shutterstock settings in the app.",
        "4. Вставьте эти данные в настройки Adobe Stock в приложении.": "4. Paste these credentials into the Adobe Stock settings in the app.",
        "5 ч. назад": "5h ago",
        "60 FPS (Стандартный)": "60 FPS (Standard)",
        "Email": "Email",
        "English": "English",
        "FTP Логи": "FTP Logs",
        "Google AdMob Rewarded • Смотрите видео для бесплатных слотов": "Google AdMob Rewarded • Watch video for free upload slots",
        "Google OAuth Client ID": "Google OAuth Client ID",
        "Google OAuth Client ID (необязательно)": "Google OAuth Client ID (optional)",
        "Google Фото и Drive": "Google Photos & Drive",
        "Google Фото и Google Диск": "Google Photos & Google Drive",
        "Language changed to English": "Language changed to English",
        "Offline": "Offline",
        "SEO-Максимум": "SEO Max",
        "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime и др.": "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime & more.",
        "SmartStock является независимым инструментом и не связан, не авторизован и не спонсируется Shutterstock, Adobe Stock, Getty Images, Depositphotos, Freepik, Alamy, Dreamstime, 123RF, Pond5 или Google. Все товарные знаки и названия брендов принадлежат их правообладателям.": "SmartStock is an independent software tool and is not affiliated with, authorized, maintained, sponsored, or endorsed by Shutterstock, Adobe Stock, Getty Images, Depositphotos, Freepik, Alamy, Dreamstime, 123RF, Pond5, or Google. All trademarks, service marks, and brand names belong to their respective owners.",
        "АКТИВЕН": "ACTIVE",
        "Авто-апскейл включён — работает при добавлении фото": "Auto-upscale enabled — works when adding photos",
        "Авто-апскейл отключён": "Auto-upscale disabled",
        "Автозагрузка папки (Планировщик)": "Folder Auto-upload (Scheduler)",
        "Автоматизируйте рутину и отправляйте сотни фото и видео на 10+ стоков в один клик.": "Automate the routine and submit hundreds of photos and videos to 10+ stock agencies in one click.",
        "Автоматическая выгрузка на 10+ стоков и безлимитные теги ИИ": "Automatic upload to 10+ stocks & unlimited AI tags",
        "Автоматический Апскейл": "Auto Upscale",
        "Автоповтор при сбоях": "Auto-retry on failures",
        "Автоповтор при сбоях (3 попытки)": "Auto-retry on failures (3 attempts)",
        "Авторизация...": "Signing in...",
        "Агентства": "Agencies",
        "Адрес сервера (IP:Порт)": "Server Address (IP:Port)",
        "Адрес электронной почты": "Email Address",
        "Активен": "Active",
        "Активно": "Active",
        "Активных подписок не найдено. Если вы совершали покупку, убедитесь, что вошли под нужным Apple ID.": "No active subscriptions found. If you previously purchased, ensure you are signed into the correct Apple ID.",
        "Анализ изображения": "Analyze Image",
        "Анализируем...": "Analyzing...",
        "Без названия": "Untitled",
        "Безлимитная очередь файлов": "Unlimited File Queue",
        "Безлимитный ИИ, 10+ стоков и автозагрузка": "Unlimited AI, 10+ stocks & auto-upload",
        "Безлимитный ИИ-анализ кадра": "Unlimited AI Media Analysis",
        "Безопасное соединение по стандарту OAuth 2.0": "Secure connection via OAuth 2.0 standard",
        "Бесплатно": "Free",
        "В ОЧЕРЕДИ": "IN QUEUE",
        "В бесплатной версии доступно до 2 стоков. Перейдите на PRO для одновременной выгрузки на все стоки!": "Free tier allows up to 2 stocks. Upgrade to PRO to upload to all stocks simultaneously!",
        "В ожидании": "Pending",
        "В очереди": "In Queue",
        "В разделе «APIs & Services» → «Library» найдите «Photos Library API» (а также «Google Drive API») и нажмите кнопку «Enable» (Включить).": "In 'APIs & Services' → 'Library', find 'Photos Library API' (and 'Google Drive API') and click 'Enable'.",
        "В разделе «Credentials» нажмите «+ Create Credentials» → «OAuth client ID». Выберите тип приложения «iOS» (Bundle ID: com.samvel.smartstock.SmartStock) или «Web application».": "In 'Credentials', click '+ Create Credentials' → 'OAuth client ID'. Select application type 'iOS' (Bundle ID: com.samvel.smartstock.SmartStock) or 'Web application'.",
        "В разделе «OAuth consent screen» выберите тип «External» (Внешний), укажите имя приложения и ваш email. В блоке «Test users» добавьте свой Gmail-адрес.": "In 'OAuth consent screen', select 'External', enter app name and your email. In 'Test users', add your Gmail address.",
        "ВЫГОДА 50% • 3 ДНЯ БЕСПЛАТНО": "50% OFF • 3 DAYS FREE",
        "Важно для Google / Apple": "Important for Google / Apple",
        "Ваш Client ID из Google Cloud Console...": "Your Client ID from Google Cloud Console...",
        "Ваш умный микростоковый менеджер": "Your smart microstock manager",
        "Ваши покупки успешно восстановлены! Доступ к SmartStock PRO открыт.": "Your purchases have been successfully restored! SmartStock PRO is active.",
        "Введите ваш Email": "Please enter your Email",
        "Введите ваш пароль": "Please enter your password",
        "Введите вашу электронную почту для синхронизации аккаунта.": "Enter your email address to synchronize your account.",
        "Введите личный токен аутентификации API": "Enter your personal API authentication token",
        "Видео": "Videos",
        "Видеозапись Google Фото": "Google Video",
        "Видеофайлы будут отправляться строго по одному друг за другом для стабильности FTP.": "Video files will be uploaded strictly one by one to ensure FTP stability.",
        "Видеофайлы отправляются строго по очереди один за другим без перегрева процессора.": "Video files are uploaded strictly one by one to avoid CPU overheating.",
        "Включите Photos Library API": "Enable Photos Library API",
        "Включить авто-апскейл": "Enable Auto-Upscale",
        "Внимание: Данный сток требует SFTP. Plain FTP-соединение для него может быть недоступно.": "Warning: This stock requires SFTP. Plain FTP connection may not be available.",
        "Войдите в аккаунт, чтобы синхронизировать ваши настройки стоков и ключи API в облаке.": "Sign in to synchronize your stock settings and API keys in the cloud.",
        "Войдите с Google-аккаунтом": "Sign in with Google Account",
        "Войти": "Sign In",
        "Войти через Помощник (авто-настройка)": "Sign in via Assistant (auto-setup)",
        "Восстановить": "Restore",
        "Вошли через Google или Apple?": "Signed in with Google or Apple?",
        "Все премиум-функции и безлимитный ИИ активны": "All premium features and unlimited AI are active",
        "Все стоки": "All Stocks",
        "Все файлы": "All files",
        "Всего": "Total",
        "Всего ~249 ₽ в месяц. Списание после 3-дневного триала.": "Save 50%. Billed annually after 3-day free trial.",
        "Всего ~%@ в месяц. Списание после 3-дневного триала.": "Just ~%@ / mo. Billed annually after 3-day trial.",
        "Вставьте Client ID в приложение": "Paste Client ID into App",
        "Вставьте Client ID из Google Cloud Console...": "Paste Client ID from Google Cloud Console...",
        "Вставьте ключ API...": "Paste API key...",
        "Вставьте ключ в приложение": "Paste Key into App",
        "Вся история загрузок будет удалена. Это действие нельзя отменить.": "All upload history will be deleted. This action cannot be undone.",
        "Вход в систему": "Sign In",
        "Вход с Google": "Sign in with Google",
        "Вход через": "Sign in via",
        "Вход через Google / Apple": "Sign in with Google / Apple",
        "Вы уверены, что хотите выйти из аккаунта?": "Are you sure you want to sign out?",
        "Выберите снимки, чтобы запустить ИИ-подбор метаданных и отправить их на микростоки.": "Select photos to start AI metadata generation and upload to microstocks.",
        "Выбирайте исходные видео и фото прямо из вашего облачного архива для публикации на стоках.": "Select original videos and photos directly from your cloud library to publish on microstocks.",
        "Выбрать": "Select",
        "Выбрать стоки...": "Select Stocks...",
        "Выбрать...": "Select...",
        "Выгрузить на стоки": "Upload to Stocks",
        "Выгрузка на все 10+ стоков сразу": "Simultaneous Upload to 10+ Stocks",
        "Выйти": "Sign Out",
        "Выйти из аккаунта": "Sign Out",
        "Высокий": "High",
        "Высокое качество индексации через модели GPT-4o и GPT-4o-mini.": "High-quality indexing via GPT-4o and GPT-4o-mini models.",
        "Выход из Google Фото выполнен": "Signed out of Google Photos",
        "ГОТОВ": "READY",
        "Галерея": "Gallery",
        "Генерация ключевых слов и описаний с помощью ИИ": "AI Keywording and Description Generator",
        "Генерация коммерческих названий, описаний и до 50 тегов через Gemini 2.5, GPT-4o, Claude": "Generate commercial titles, descriptions and up to 50 tags via Gemini 2.5, GPT-4o, Claude",
        "Глубокое понимание коммерческой эстетики через Claude 3.5 Sonnet.": "Deep understanding of commercial aesthetics via Claude 3.5 Sonnet.",
        "Годовая подписка": "Yearly Subscription",
        "Готово": "Done",
        "Готовы к загрузке": "Ready to upload",
        "Демо": "Demo",
        "Демо-описание: Живописный закат солнца над горным хребтом.": "Demo description: Scenic sunset over a mountain range.",
        "Детали фотографии": "Photo Details",
        "Динамика загрузок": "Upload Dynamics",
        "Для выгрузки из приложения вам необходимо использовать специальный FTP-пароль, сгенерированный в личном кабинете автора.": "To upload from the app, you need to use a special FTP password generated in your contributor dashboard.",
        "Добавить": "Add",
        "Добавить слово": "Add keyword",
        "Добавить фото": "Add Photos",
        "Дополнительные параметры сервера": "Advanced Server Parameters",
        "Драматичный закат в горах (Демо)": "Dramatic Sunset in Mountains (Demo)",
        "Ежемесячный доступ со всеми обновлениями.": "Monthly access with all updates included.",
        "Если в окне Google выводится 'invalid_client (401)', введите ваш свой Client ID из Google Cloud Console (APIs & Services -> Credentials).": "If Google shows 'invalid_client (401)', enter your own Client ID from Google Cloud Console (APIs & Services -> Credentials).",
        "Если вы регистрировались на фотостоках через аккаунт Google или Apple, прямой вход по паролю этих сервисов не поддерживается для FTP/SFTP загрузки (это техническое ограничение самих стоков).": "If you registered on stock agencies via a Google or Apple account, direct login using their password is not supported for FTP/SFTP upload (this is a technical limitation of the stock agencies themselves).",
        "Еще не запускался": "Never ran",
        "За последние 30 дней": "Last 30 Days",
        "Забрать +5 фото": "Claim +5 Photos",
        "Заголовок": "Title",
        "Заголовок фото": "Photo title",
        "Загружено": "Uploaded",
        "Загрузить все": "Upload All",
        "Загрузить новый контент": "Upload New Content",
        "Загрузка видео по очереди": "Sequential video upload",
        "Загрузка видео по очереди (Строго 1 за 1)": "Sequential video upload (Strictly 1 by 1)",
        "Загрузка видео по очереди включена": "Sequential video upload enabled",
        "Загрузка видео по очереди отключена": "Sequential video upload disabled",
        "Загрузка медиафайлов...": "Loading media files...",
        "Загрузка файла": "Uploading file",
        "Загрузка фото по очереди": "Sequential photo upload",
        "Загрузка фото по очереди включена": "Sequential photo upload enabled",
        "Загрузка фото по очереди отключена": "Sequential photo upload disabled",
        "Загрузка через ПК-сервер": "Upload via PC Server",
        "Загрузка...": "Loading...",
        "Загрузки": "Uploads",
        "Закрыть": "Close",
        "Заново": "Regenerate",
        "Заполнить ИИ": "Fill with AI",
        "Заполнить все ИИ": "Fill All with AI",
        "Запуск проверки...": "Running check...",
        "Запустить ИИ-анализ": "Run AI Analysis",
        "Запустить проверку сейчас": "Run Check Now",
        "Запущен ИИ-анализ для": "AI analysis started for",
        "Зарегистрироваться": "Register",
        "ИИ": "AI Engines",
        "ИИ АНАЛИЗ": "AI ANALYZE",
        "ИИ Анализ": "AI Analysis",
        "ИИ для выбранных": "AI for Selected",
        "ИИ провайдеры": "AI Providers",
        "ИИ успешно заполнил метаданные для": "AI successfully generated metadata for",
        "ИИ-Ассистент": "AI Assistant",
        "Из буфера": "From Clipboard",
        "Изменить": "Change",
        "Импорт видео и фото из архива Google Фото": "Import videos and photos from Google Photos archive",
        "Импортировать": "Import",
        "Импортировать в очередь": "Import to Queue",
        "Имя пользователя (логин)": "Username (login)",
        "Имя хоста (сервер)": "Hostname (server)",
        "Инструкция Google Фото": "Google Photos Guide",
        "Инструкция для Adobe Stock": "Adobe Stock Instructions",
        "Инструкция для Shutterstock": "Shutterstock Instructions",
        "Инструкция по настройке FTP для": "FTP setup instructions for",
        "Интегрированные фотостоки": "Integrated Stock Agencies",
        "Интеллектуальный Помощник": "Intelligent Assistant",
        "Интеллектуальный ассистент": "AI Assistant",
        "Интервал проверки": "Check Interval",
        "Интерфейс": "Interface",
        "Интерфейс и Оформление": "Interface & Appearance",
        "Использовано диска:": "Disk space used:",
        "Используется для прямого доступа к API Google Фото и Drive.": "Used for direct access to Google Photos and Drive APIs.",
        "Используйте ваш обычный личный аккаунт Google для входа в сервис.": "Use your regular personal Google account to sign in.",
        "История выгрузок": "Upload History",
        "История доходов": "Earnings History",
        "История загрузок": "Upload History",
        "История пуста": "History is empty",
        "КЛЮЧЕВЫЕ СЛОВА (Генерация ИИ)": "KEYWORDS (AI Generation)",
        "Каждые": "Every",
        "Как получить API-ключ": "How to Get API Key",
        "Категории": "Categories",
        "Категории (Макс. 2)": "Categories (Max 2)",
        "Категории не выбраны. Выберите до 2 категорий.": "No categories selected. Choose up to 2 categories.",
        "Ключевые слова": "Keywords",
        "Ключевые слова отсутствуют. Запустите ИИ-анализ.": "No keywords found. Run AI analysis.",
        "Коммерческий": "Commercial",
        "Копировать": "Copy",
        "Коэффициент (масштаб)": "Scale Factor",
        "Креативный": "Creative",
        "Кэш скачанных медиафайлов очищен!": "Downloaded media cache cleared!",
        "Кэширование включено": "Caching enabled",
        "Лимит достигнут": "Limit reached",
        "Локальный ПК-сервер": "Local PC Server",
        "МЕТАДАННЫЕ": "METADATA",
        "Максимум продаж на стоках": "Maximize Your Microstock Sales",
        "Мгновенное создание таблиц метаданных для любых агентств": "Instant metadata spreadsheet creation for any agency",
        "Медиафайлов не найдено. Проверьте, включен ли Photos/Drive API в Google Cloud.": "No media files found. Check if Photos/Drive API is enabled in Google Cloud.",
        "Меньше 2 МБ": "Less than 2 MB",
        "Меньше 4 МБ (Рекомендуется)": "Less than 4 MB (Recommended)",
        "Меньше 8 МБ": "Less than 8 MB",
        "Месячная подписка": "Monthly Subscription",
        "Метаданные": "Metadata",
        "Метрики": "Metrics",
        "Мини": "Mini",
        "Мой аккаунт": "My Account",
        "НАВСЕГДА": "LIFETIME",
        "На удержании": "On Hold",
        "Награда получена! 🎉": "Reward Earned! 🎉",
        "Награда через:": "Reward in:",
        "Нажмите «Create API key»": "Click 'Create API key'",
        "Нажмите «Create Key», задайте имя и скопируйте сформированный токен.": "Click 'Create Key', specify a name and copy the generated token.",
        "Нажмите для выбора или перетащите": "Tap to browse or drop here",
        "Нажмите кнопку «+ Create new secret key», укажите название и сохраните ключ.": "Click '+ Create new secret key', enter a name and save the key.",
        "Нажмите на агентство ниже, чтобы зайти в личный кабинет через встроенный браузер.": "Tap on an agency below to log in to your account via the built-in browser.",
        "Нажмите синюю кнопку «Create API key» (Создать ключ API) и выберите или создайте проект.": "Click the blue 'Create API key' button and select or create a project.",
        "Название": "Title",
        "Настроен": "Configured",
        "Настройка Google Фото": "Google Photos Setup",
        "Настройки": "Settings",
        "Настройки сохранены!": "Settings saved!",
        "Настройки стоков": "Stock Settings",
        "Настройки стоков для фото": "Stock settings for photo",
        "Настройки успешно сохранены!": "Settings successfully saved!",
        "Настройте OAuth Consent Screen": "Configure OAuth Consent Screen",
        "Настройте ИИ для мгновенной индексации ваших кадров. Генерация коммерческих названий и SEO-тегов.": "Configure AI for instant indexing of your frames. Generation of commercial titles and SEO tags.",
        "Началась отправка": "Started uploading",
        "Не выбрана": "Not selected",
        "Не настроен": "Not Configured",
        "Не подключено": "Not Connected",
        "Не удалось подключиться к App Store. Пожалуйста, проверьте интернет-соединение.": "Could not connect to App Store. Please check your internet connection.",
        "Не удалось получить доступ к папке": "Could not access the folder",
        "Недавние": "Recents",
        "Некорректный формат Email": "Invalid Email format",
        "Неограниченный импорт исходных медиафайлов прямо из облака": "Unlimited direct import of media files from cloud storage",
        "Нет данных": "No data",
        "Нет загрузок": "No uploads",
        "Нет новых файлов для ИИ-анализа.": "No new files for AI analysis.",
        "Нет подключённых стоков": "No connected stock agencies",
        "Нет файлов, готовых к отправке.": "No files ready for upload.",
        "Нужна настройка": "Setup required",
        "ОБЛАКО GOOGLE ФОТО": "GOOGLE PHOTOS CLOUD",
        "ОК": "OK",
        "Облачная синхронизация": "Cloud Sync",
        "Обмен кода авторизации...": "Exchanging auth code...",
        "Обнаружены данные для настройки": "Configuration credentials detected for",
        "Общий баланс": "Total Balance",
        "Один платёж раз и навсегда. Без подписок.": "One-time payment forever. No recurring charges.",
        "Ожидает подтверждения": "Pending Approval",
        "Ок": "OK",
        "Описание": "Description",
        "Описание отсутствует": "No description",
        "Отключено от Google Фото": "Disconnected from Google Photos",
        "Откройте Anthropic Console": "Open Anthropic Console",
        "Откройте Google AI Studio": "Open Google AI Studio",
        "Откройте OpenAI Platform": "Open OpenAI Platform",
        "Открытие окна авторизации Google...": "Opening Google authorization window...",
        "Открыть Adobe Stock Contributor": "Open Adobe Stock Contributor",
        "Открыть Anthropic Console": "Open Anthropic Console",
        "Открыть Google Cloud Console": "Open Google Cloud Console",
        "Открыть OpenAI API Keys": "Open OpenAI API Keys",
        "Открыть submit.shutterstock.com": "Open submit.shutterstock.com",
        "Отмена": "Cancel",
        "Отправить": "Send",
        "Отправить выбр.": "Upload Selected",
        "Отправить на стоки": "Send to Stocks",
        "Отправлено": "Sent",
        "Очередь": "Queue",
        "Очередь выгрузки": "Upload Queue",
        "Очередь пуста": "Queue is empty",
        "Очистить": "Clear",
        "Очистить историю": "Clear History",
        "Очистить историю?": "Clear history?",
        "Очистка остаточного кэша": "Clear residual cache",
        "Ошибка ИИ-анализа для": "AI analysis error for",
        "Ошибка выгрузки": "Upload error",
        "Ошибка загрузки": "Upload Error",
        "Ошибка соединения с": "Connection error with",
        "Ошибка сохранения папки:": "Error saving folder:",
        "Ошибка сохранения папки: ": "Error saving folder: ",
        "Ошибка:": "Error:",
        "Ошибка: Нет активных стоков или не введены логин/пароль!": "Error: No active stock agencies configured or credentials missing!",
        "Ошибки": "Errors",
        "Ошибок": "Errors",
        "ПРОГНОЗ ПОПУЛЯРНОСТИ (Рыночный анализ ИИ)": "POPULARITY PREDICTION (AI Market Analysis)",
        "Пакетная обработка и загрузка сотен фото и 4K/8K видео без пауз и ограничений": "Batch process and upload hundreds of photos and 4K/8K videos without limits",
        "Память и Очистка кэша": "Storage & Cache Management",
        "Папка для импорта": "Import Folder",
        "Папка для сканирования": "Scan Folder",
        "Папка успешно выбрана:": "Folder successfully selected:",
        "Папка успешно выбрана: ": "Folder successfully selected: ",
        "Параллельные потоки:": "Parallel streams:",
        "Параллельные потоки: ": "Parallel streams: ",
        "Параметры": "Settings",
        "Параметры Google Фото": "Google Photos Settings",
        "Параметры SFTP / FTP для": "SFTP / FTP parameters for",
        "Параметры выгрузки": "Upload Parameters",
        "Параметры выгрузки и очередность": "Upload Parameters & Priority",
        "Параметры подключения": "Connection Parameters",
        "Параметры системы": "System Settings",
        "Пароль": "Password",
        "Пароль должен содержать не менее 6 символов": "Password must contain at least 6 characters",
        "Перейдите в консоль разработчика Google Cloud и создайте новый бесплатный проект (например, SmartStock).": "Go to Google Cloud Developer Console and create a new free project (e.g., SmartStock).",
        "Перейдите в раздел «Агентства» и настройте учётные данные для Shutterstock, Adobe Stock или других стоков — статистика загрузок появится здесь автоматически.": "Go to Agencies section and configure credentials for Shutterstock, Adobe Stock or other stocks — upload statistics will appear here automatically.",
        "Перейдите на официальный портал Google AI Studio (aistudio.google.com).": "Go to the official Google AI Studio portal (aistudio.google.com).",
        "Перейдите на страницу ключей (console.anthropic.com/settings/keys).": "Go to the keys page (console.anthropic.com/settings/keys).",
        "Перейдите на страницу ключей API (platform.openai.com/api-keys).": "Go to the API keys page (platform.openai.com/api-keys).",
        "Перейти в настройки агентств →": "Go to agency settings →",
        "Перейти на SmartStock PRO": "Upgrade to SmartStock PRO",
        "Планировщик": "Scheduler",
        "Планировщик выгрузки": "Upload Scheduler",
        "По стокам": "By Stock Agency",
        "Подготовка воспроизведения видео...": "Preparing video playback...",
        "Подключение": "Connection",
        "Подключение Google Фото": "Connect Google Photos",
        "Подключено": "Connected",
        "Подключено к Google Фото": "Connected to Google Photos",
        "Подключить": "Connect",
        "Подписка": "Subscription",
        "Подписка продлевается автоматически, пока не будет отменена в настройках Apple ID не менее чем за 24 часа до окончания текущего периода.": "Subscription automatically renews unless canceled in Apple ID Settings at least 24 hours before the end of the current period.",
        "Подробнее": "Details",
        "Пожалуйста, введите API-ключ перед проверкой.": "Please enter an API key before verifying.",
        "Пожалуйста, введите ваш Google Client ID в параметрах системы.": "Please enter your Google Client ID in system settings.",
        "Пожалуйста, введите логин и пароль.": "Please enter username and password.",
        "Пожизненный PRO": "Lifetime PRO",
        "Позволяет отправлять фото через программу на вашем компьютере.": "Allows sending photos via the program on your computer.",
        "Позволяет отправлять фото через программу на вашем компьютере. Полезно, если на телефоне блокируется FTPS к Shutterstock.": "Allows sending photos via the app on your computer. Useful if FTPS to Shutterstock is blocked on the phone.",
        "Поздравляем! SmartStock PRO успешно активирован! 🎉": "Congratulations! SmartStock PRO is now active! 🎉",
        "Поиск по файлам...": "Search files...",
        "Поиск фото, альбомов...": "Search photos, albums...",
        "Показать все": "View All",
        "Покупки": "Sales",
        "Политика конфиденциальности": "Privacy Policy",
        "Получить ключ в Google AI Studio": "Get Key in Google AI Studio",
        "Попробовать 3 дня бесплатно": "Try 3 Days Free",
        "Порог срабатывания": "Trigger Threshold",
        "Порядок": "Reorder",
        "Порядок очереди": "Queue Order",
        "Последний запуск": "Last run",
        "Потоки параллельной загрузки": "Parallel Upload Streams",
        "Пошаговое руководство по получению Client ID": "Step-by-step guide to obtaining Client ID",
        "Правовая информация и товарные знаки": "Legal Information & Trademarks",
        "Предел частоты кадров": "Frame Rate Limit",
        "При активации планировщика система будет проверять новые фото в выбранной папке и отправлять их в фоновом режиме.": "When activated, the system will check for new photos in the selected folder and upload them in the background.",
        "При активации планировщика система будет проверять новые фото и отправлять их в фоновом режиме.": "When activated, the system will check for new photos and upload them in the background.",
        "Приложение работает как прямой проводник: файлы отправляются без дублирования на диск телефона.": "The app operates as a direct explorer: files are uploaded without duplicating to device storage.",
        "Применить к фото": "Apply to Photo",
        "Проверено": "Approved",
        "Проверить соединение": "Test Connection",
        "Проверка ключа": "Key Verification",
        "Проверка папки завершена!": "Folder check completed!",
        "Проверка подключения к": "Verifying connection to",
        "Проверка соединения...": "Verifying connection...",
        "Проверка...": "Testing...",
        "Продолжить": "Continue",
        "Продолжить с SmartStock PRO": "Continue with SmartStock PRO",
        "Промпт для ИИ-анализа": "Prompt for AI Analysis",
        "Промпт определяет формат возвращаемого JSON-файла с заголовком и ключевыми словами.": "The prompt specifies the structure of the JSON file containing title and keywords.",
        "Размер": "Size",
        "Регистрация": "Register",
        "Редактировать": "Edit",
        "Режим проводника (Прямая выгрузка без кэша)": "Explorer Mode (Direct upload without cache)",
        "Режим проводника активен: 0 МБ кэша": "Explorer mode active: 0 MB cache",
        "Результаты анализа": "Analysis Results",
        "Рекомендуемый провайдер: самый быстрый и бесплатный доступ.": "Recommended provider: fastest and free access.",
        "Репортажный": "Editorial",
        "Русский": "Russian",
        "Светлая": "Light",
        "Сводка активности": "Activity Summary",
        "Связь с App Store...": "Connecting to App Store...",
        "Сервер выгрузки:": "Upload server:",
        "Сжатие JPEG перед загрузкой": "Compress JPEG before upload",
        "Синхронизация": "Sync",
        "Синхронизация профиля активна": "Profile sync is active",
        "Синхронизация:": "Sync:",
        "Синхронизация: ": "Sync: ",
        "Системная": "System",
        "Системные уведомления": "System Notifications",
        "Сканировать": "Scan",
        "Скопировано!": "Copied!",
        "Скопировать": "Copy",
        "Скопировать все": "Copy All",
        "Скопируйте и вставьте ключ": "Copy and Paste Key",
        "Скопируйте ключ (начинается на «sk-...») и вставьте в поле OpenAI в настройках ИИ.": "Copy the key (starts with 'sk-...') and paste it into the OpenAI field in AI settings.",
        "Скопируйте ключ (начинается на «sk-ant-...») и вставьте в поле Claude в настройках ИИ.": "Copy the key (starts with 'sk-ant-...') and paste it into the Claude field in AI settings.",
        "Скопируйте полученный идентификатор (вида xxxx.apps.googleusercontent.com) и вставьте в поле Client ID в приложении.": "Copy the generated identifier (like xxxx.apps.googleusercontent.com) and paste into the Client ID field in the app.",
        "Скопируйте сгенерированный ключ (начинается на «AIzaSy...») и вставьте в приложении в поле Gemini.": "Copy the generated key (starts with 'AIzaSy...') and paste it into the Gemini field in the app.",
        "Создайте API-ключ": "Create API Key",
        "Создайте OAuth Client ID": "Create OAuth Client ID",
        "Создайте новый секретный ключ": "Create New Secret Key",
        "Создайте проект в Google Cloud": "Create a Project in Google Cloud",
        "Сохранить все настройки": "Save All Settings",
        "Сохранить изменения": "Save Changes",
        "Спонсорский ролик": "Sponsored Video",
        "Стандартный": "Standard",
        "Статистика": "Insights",
        "Статистика очереди": "Queue Stats",
        "Статус": "Status",
        "Статус:": "Status:",
        "Стоки": "Stocks",
        "Тема оформления": "Theme",
        "Темная": "Dark",
        "Только видео": "Videos only",
        "Только фото": "Photos only",
        "У вас нет аккаунта?": "Don't have an account?",
        "Увеличение 2x (Бикубическое)": "Scale 2x (Bicubic)",
        "Увеличение 4x (Нейросеть)": "Scale 4x (Neural Network)",
        "Удалить": "Delete",
        "Удалить из очереди": "Remove from Queue",
        "Уже есть аккаунт?": "Already have an account?",
        "Условия использования (EULA)": "Terms of Use (EULA)",
        "Успешная авторизация в Google": "Successfully authorized with Google",
        "Успешная выгрузка": "Upload Successful",
        "Успешно": "Success",
        "Успешное соединение с сервером": "Successfully connected to server",
        "Успешный вход через Apple!": "Successfully signed in with Apple!",
        "Успешный вход через Google!": "Successfully signed in with Google!",
        "Учетные данные обнаружены": "Credentials detected",
        "Файл": "File",
        "Файлы на устройстве": "Device Files",
        "Файлы не найдены": "Files not found",
        "Фоновая обработка завершена. Новых файлов загружено: ": "Background processing completed. New files uploaded: ",
        "Фоновый авто-сканер": "Background auto-scanner",
        "Фоновый планировщик выгрузки": "Background Upload Scheduler",
        "Фото": "Photos",
        "Фотографии будут отправляться строго по одной по очереди.": "Photo files will be uploaded strictly one by one in sequence.",
        "Фотографии будут отправляться строго последовательно по одной.": "Photos will be uploaded strictly one by one.",
        "Фотография Google Фото": "Google Photo",
        "Частота кадров изменена на ": "Frame rate changed to ",
        "Частота кадров: ": "Frame rate: ",
        "Экспорт CSV и метаданных": "CSV & Metadata Export",
        "Эффективность агентств": "Performance by Agency",
        "Язык изменён на Русский": "Language changed to Russian",
        "Язык интерфейса": "App Language",
        "Язык приложения": "App Language",
        "всего": "total",
        "готовность": "readiness",
        "загрузок": "uploads",
        "записей": "records",
        "из": "of",
        "или": "or",
        "подключено": "connected",
        "поток": "stream",
        "потока": "streams",
        "потоков": "streams",
        "успешно загружен на стоки!": "successfully uploaded to stocks!",
        "успешно загружен!": "successfully uploaded!",
        "файлов...": "files...",
        "час": "hour",
        "часа": "hours",
        "часов": "hours"
    ]
    
    private static let hyTranslations: [String: String] = [
        " — применится при запуске": " — կկիրառվի վերագործարկելիս",
        " — применится при следующей загрузке": " — կկիրառվի հաջորդ վերբեռնման ժամանակ",
        "+5 бонусных фото начислены в вашу очередь": "+5 բոնուսային լուսանկար ավելացվել է ձեր հերթին",
        "1 д. назад": "1օր առաջ",
        "1. Войдите в кабинет автора на submit.shutterstock.com.": "1. Մուտք գործեք հեղինակի կաբինետ submit.shutterstock.com կայքում:",
        "1. Войдите в личный кабинет автора на contributor.adobestock.com.": "1. Մուտք գործեք հեղինակի անձնական կաբինետ contributor.adobestock.com կայքում:",
        "100K+ Загрузок": "100K+ Ներբեռնում",
        "12 ч. назад": "12ժ առաջ",
        "120 FPS (Ультра-плавность)": "120 FPS (Գերսահուն)",
        "2 ч. назад": "2ժ առաջ",
        "2. Перейдите в 'Настройки учетной записи' (нажав на свой профиль в правом верхнем углу).": "2. Անցեք «Հաշվի կարգավորումներ» բաժին (սեղմելով ձեր պրոֆիլին վերևի աջ անկյունում):",
        "2. Перейдите в настройки аккаунта 'Account Settings'.": "2. Անցեք հաշվի կարգավորումներ «Account Settings»:",
        "3. В подразделе 'Настройки FTP' вы увидите ваш персональный логин (ID) и сгенерированный FTP-пароль.": "3. «FTP կարգավորումներ» ենթաբաժնում դուք կտեսնեք ձեր անձնական օգտանունը (ID) և գեներացված FTP-գաղտնաբառը:",
        "3. Найдите раздел FTP и скопируйте предоставленные учетные данные (обычно логином является ваш email).": "3. Գտեք FTP բաժինը և պատճենեք տրամադրված տվյալները (սովորաբար մուտքանունը ձեր էլ. հասցեն է):",
        "30 FPS (Энергосбережение)": "30 FPS (Էներգախնայողություն)",
        "4. Введите их в настройки Shutterstock в приложении.": "4. Մուտքագրեք դրանք հավելվածում Shutterstock-ի կարգավորումներում:",
        "4. Вставьте эти данные в настройки Adobe Stock в приложении.": "4. Տեղադրեք այս տվյալները հավելվածում Adobe Stock-ի կարգավորումներում:",
        "5 ч. назад": "5ժ առաջ",
        "60 FPS (Стандартный)": "60 FPS (Ստանդարտ)",
        "Email": "Էլ. հասցե",
        "English": "English",
        "FTP Логи": "FTP Լոգեր",
        "Google AdMob Rewarded • Смотрите видео для бесплатных слотов": "Google AdMob Rewarded • Դիտեք վիդեո անվճար սլոթերի համար",
        "Google OAuth Client ID": "Google OAuth Client ID",
        "Google OAuth Client ID (необязательно)": "Google OAuth Client ID (ըստ ցանկության)",
        "Google Фото и Drive": "Google Լուսանկարներ և Drive",
        "Google Фото и Google Диск": "Google Լուսանկարներ և Google Drive",
        "Language changed to English": "Language changed to English",
        "Offline": "Անցանց",
        "SEO-Максимум": "SEO-Առավելագույն",
        "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime и др.": "Shutterstock, Adobe Stock, Getty Images, Freepik, Depositphotos, Dreamstime և այլն:",
        "SmartStock является независимым инструментом и не связан, не авторизован и не спонсируется Shutterstock, Adobe Stock, Getty Images, Depositphotos, Freepik, Alamy, Dreamstime, 123RF, Pond5 и Google.": "SmartStock-ը անկախ գործիք է և կապված, լիազորված կամ հովանավորված չէ Shutterstock-ի, Adobe Stock-ի, Getty Images-ի, Depositphotos-ի, Freepik-ի, Alamy-ի, Dreamstime-ի, 123RF-ի, Pond5-ի և Google-ի կողմից։",
        "SmartStock является независимым инструментом и не связан, не авторизован и не спонсируется Shutterstock, Adobe Stock, Getty Images, Depositphotos, Freepik, Alamy, Dreamstime, 123RF, Pond5 или Google. Все товарные знаки и названия брендов принадлежат их правообладателям.": "SmartStock-ը անկախ գործիք է և կապված, լիազորված կամ հովանավորված չէ Shutterstock-ի, Adobe Stock-ի, Getty Images-ի, Depositphotos-ի, Freepik-ի, Alamy-ի, Dreamstime-ի, 123RF-ի, Pond5-ի կամ Google-ի կողմից։ Բոլոր ապրանքանիշերը պատկանում են իրենց իրավատերերին։",
        "АКТИВЕН": "ԱԿՏԻՎ Է",
        "Авто-апскейл включён — работает при добавлении фото": "Ավտոմատ ափսքեյլը միացված է — աշխատում է լուսանկար ավելացնելիս",
        "Авто-апскейл отключён": "Ավտոմատ ափսքեյլն անջատված է",
        "Автозагрузка папки (Планировщик)": "Թղթապանակի ավտո-վերբեռնում (Պլանավորող)",
        "Автоматизируйте рутину и отправляйте сотни фото и видео на 10+ стоков в один клик.": "Ավտոմատացրեք առօրյան և ուղարկեք հարյուրավոր նկարներ ու վիդեոներ 10+ ստոկեր մեկ սեղմումով:",
        "Автоматическая выгрузка на 10+ стоков и безлимитные теги ИИ": "Ավտոմատ վերբեռնում 10+ ստոկեր և անսահմանափակ ԱԻ թեգեր",
        "Автоматический Апскейл": "Ավտոմատ Ափսքեյլ",
        "Автоповтор при сбоях": "Ավտո-կրկնում սխալների դեպքում",
        "Автоповтор при сбоях (3 попытки)": "Ավտո-կրկնում սխալների դեպքում (3 փորձ)",
        "Авторизация...": "Մուտքի հաստատում...",
        "Агентства": "Գործակալություններ",
        "Адрес сервера (IP:Порт)": "Սերվերի հասցե (IP:Port)",
        "Адрес электронной почты": "Էլ. փոստի հասցե",
        "Активен": "Ակտիվ է",
        "Активно": "Ակտիվ է",
        "Активных подписок не найдено. Если вы совершали покупку, убедитесь, что вошли под нужным Apple ID.": "Ակտիվ բաժանորդագրություններ չեն գտնվել: Եթե նախկինում գնել եք, համոզվեք, որ մուտք եք գործել ճիշտ Apple ID-ով:",
        "Анализ изображения": "Պատկերի վերլուծություն",
        "Анализируем...": "Վերլուծվում է...",
        "Без названия": "Անանուն",
        "Безлимитная очередь файлов": "Ֆայլերի անսահմանափակ հերթ",
        "Безлимитный ИИ, 10+ стоков и автозагрузка": "Անսահմանափակ ԱԻ, 10+ ստոկեր և ավտովերբեռնում",
        "Безлимитный ИИ-анализ кадра": "Անսահմանափակ ԱԻ վերլուծություն",
        "Безопасное соединение по стандарту OAuth 2.0": "Ապահով միացում OAuth 2.0 ստանդարտով",
        "Бесплатно": "Անվճար",
        "В ОЧЕРЕДИ": "ՀԵՐԹՈՒՄ",
        "В бесплатной версии доступно до 2 стоков. Перейдите на PRO для одновременной выгрузки на все стоки!": "Անվճար տարբերակում հասանելի է մինչև 2 ստոկ: Անցեք PRO-ի՝ բոլոր ստոկեր միաժամանակ վերբեռնելու համար!",
        "В ожидании": "Սպասման մեջ",
        "В очереди": "Հերթում",
        "В разделе «APIs & Services» → «Library» найдите «Photos Library API» (а также «Google Drive API») и нажмите кнопку «Enable» (Включить).": "«APIs & Services» → «Library» բաժնում գտեք «Photos Library API»-ն (և «Google Drive API»-ն) ու սեղմեք «Enable» (Միացնել):",
        "В разделе «Credentials» нажмите «+ Create Credentials» → «OAuth client ID». Выберите тип приложения «iOS» (Bundle ID: com.samvel.smartstock.SmartStock) или «Web application».": "«Credentials» բաժնում սեղմեք «+ Create Credentials» → «OAuth client ID»: Ընտրեք հավելվածի տեսակը՝ «iOS» (Bundle ID: com.samvel.smartstock.SmartStock) կամ «Web application»:",
        "В разделе «OAuth consent screen» выберите тип «External» (Внешний), укажите имя приложения и ваш email. В блоке «Test users» добавьте свой Gmail-адрес.": "«OAuth consent screen» բաժնում ընտրեք «External» տեսակը, նշեք հավելվածի անվանումը և ձեր էլ. հասցեն: «Test users» դաշտում ավելացրեք ձեր Gmail հասցեն:",
        "ВЫГОДА 50% • 3 ДНЯ БЕСПЛАТНО": "ՇԱՀԱՎԵՏ 50% • 3 ՕՐ ԱՆՎՃԱՐ",
        "Важно для Google / Apple": "Կարևոր է Google / Apple-ի համար",
        "Ваш Client ID из Google Cloud Console...": "Ձեր Client ID-ն Google Cloud Console-ից...",
        "Ваш умный микростоковый менеджер": "Ձեր խելացի միկրոստոկային մենեջերը",
        "Ваши покупки успешно восстановлены! Доступ к SmartStock PRO открыт.": "Ձեր գնումները հաջողությամբ վերականգնվել են: SmartStock PRO մուտքը բաց է:",
        "Введите ваш Email": "Մուտքագրեք ձեր էլ. հասցեն",
        "Введите ваш пароль": "Մուտքագրեք ձեր գաղտնաբառը",
        "Введите вашу электронную почту для синхронизации аккаунта.": "Մուտքագրեք ձեր էլ. հասցեն հաշվի սինխրոնացման համար։",
        "Введите личный токен аутентификации API": "Մուտքագրեք API նույնականացման ձեր անձնական Թոքենը",
        "Видео": "Տեսանյութեր",
        "Видеофайлы отправляются строго по очереди один за другим без перегрева процессора.": "Տեսանյութերը ուղարկվում են խիստ հերթականությամբ մեկը մյուսի հետևից:",
        "Включите Photos Library API": "Միացրեք Photos Library API-ն",
        "Включить авто-апскейл": "Միացնել ավտո-ափսքեյլը",
        "Внимание: Данный сток требует SFTP. Plain FTP-соединение для него может быть недоступно.": "Ուշադրություն. Այս ստոկը պահանջում է SFTP: Սովորական FTP միացումը կարող է անհասանելի լինել:",
        "Войдите в аккаунт, чтобы синхронизировать ваши настройки стоков и ключи API в облаке.": "Մուտք գործեք հաշիվ՝ ամպում ստոկերի կարգավորումները և API բանալիները սինխրոնացնելու համար։",
        "Войдите с Google-аккаунтом": "Մուտք գործեք Google հաշվով",
        "Войти": "Մուտք գործել",
        "Войти через Помощник (авто-настройка)": "Մուտք Օգնականով (ավտո-կարգավորում)",
        "Восстановить": "Վերականգնել",
        "Вошли через Google или Apple?": "Մուտք եք գործել Google-ո՞վ թե Apple-ով",
        "Все премиум-функции и безлимитный ИИ активны": "Բոլոր պրեմիում ֆունկցիաները և անսահմանափակ ԱԻ-ն ակտիվ են",
        "Все стоки": "Բոլոր ստոկերը",
        "Всего": "Ընդհանուր",
        "Всего ~249 ₽ в месяц. Списание после 3-дневного триала.": "Տարեկան վճարում 3-օրյա անվճար փորձաշրջանից հետո:",
        "Всего ~%@ в месяц. Списание после 3-дневного триала.": "Ընդամենը ~%@ ամսական: 3-օրյա անվճար փորձաշրջանից հետո:",
        "Вставьте Client ID в приложение": "Տեղադրեք Client ID-ն հավելվածում",
        "Вставьте Client ID из Google Cloud Console...": "Տեղադրեք Client ID-ն Google Cloud Console-ից...",
        "Вставьте ключ API...": "Տեղադրեք API բանալին...",
        "Вставьте ключ в приложение": "Տեղադրեք բանալին հավելվածում",
        "Вся история загрузок будет удалена. Это действие нельзя отменить.": "Վերբեռնումների ամբողջ պատմությունը կջնջվի: Այս գործողությունը հնարավոր չէ չեղարկել:",
        "Вход в систему": "Մուտք",
        "Вход с Google": "Մուտք Google-ով",
        "Вход через": "Մուտք",
        "Вход через Google / Apple": "Մուտք Google / Apple-ով",
        "Вы уверены, что хотите выйти из аккаунта?": "Համոզվա՞ծ եք, որ ցանկանում եք դուրս գալ հաշվից:",
        "Выберите снимки, чтобы запустить ИИ-подбор метаданных и отправить их на микростоки.": "Ընտրեք լուսանկարներ ԱԻ метаտվյալների ընտրությունը գործարկելու և միկրոստոկեր ուղարկելու համար։",
        "Выбирайте исходные видео и фото прямо из вашего облачного архива для публикации на стоках.": "Ընտրեք բնօրինակ վիդեոներ և լուսանկարներ անմիջապես ամպային արխիվից՝ ստոկերում հրապարակելու համար:",
        "Выбрать": "Ընտրել",
        "Выбрать стоки...": "Ընտրել ստոկեր...",
        "Выбрать...": "Ընտրել...",
        "Выгрузить на стоки": "Վերբեռնել ստոկեր",
        "Выгрузка на все 10+ стоков сразу": "Միաժամանակյա վերբեռնում 10+ ստոկեր",
        "Выйти": "Դուրս գալ",
        "Выйти из аккаунта": "Դուրս գալ հաշվից",
        "Высокий": "Բարձր",
        "Высокое качество индексации через модели GPT-4o и GPT-4o-mini.": "Ինդեքսավորման բարձր որակ GPT-4o և GPT-4o-mini մոդելների միջոցով:",
        "Выход из Google Фото выполнен": "Ելքը Google Լուսանկարներից կատարված է",
        "ГОТОВ": "ՊԱՏՐԱՍՏ Է",
        "Галерея": "Պատկերասրահ",
        "Генерация ключевых слов и описаний с помощью ИИ": "Բանալի բառերի և նկարագրությունների ստեղծում ԱԻ-ի միջոցով",
        "Генерация коммерческих названий, описаний и до 50 тегов через Gemini 2.5, GPT-4o, Claude": "Կոմերցիոն անվանումների, նկարագրությունների և մինչև 50 թեգերի գեներացիա Gemini 2.5, GPT-4o, Claude-ով",
        "Глубокое понимание коммерческой эстетики через Claude 3.5 Sonnet.": "Կոմերցիոն էսթետիկայի խորը ըմբռնում Claude 3.5 Sonnet-ի միջոցով:",
        "Годовая подписка": "Տարեկան բաժանորդագրություն",
        "Готово": "Պատրաստ է",
        "Готовы к загрузке": "Պատրաստ է վերբեռնման",
        "Демо": "Դեմո",
        "Демо-описание: Живописный закат солнца над горным хребтом.": "Դեմո-նկարագրություն՝ Տեսարժան մայրամուտ լեռնաշղթայի վրա։",
        "Детали фотографии": "Լուսանկարի մանրամասներ",
        "Динамика загрузок": "Վերբեռնումների դինամիկա",
        "Для выгрузки из приложения вам необходимо использовать специальный FTP-пароль, сгенерированный в личном кабинете автора.": "Հավելվածից վերբեռնելու համար անհրաժեշտ է օգտագործել հեղինակի անձնական կաբինետում գեներացված հատուկ FTP-գաղտնաբառ:",
        "Добавить": "Ավելացնել",
        "Добавить слово": "Ավելացնել բառ",
        "Добавить фото": "Ավելացնել լուսանկար",
        "Дополнительные параметры сервера": "Սերվերի լրացուցիչ կարգավորումներ",
        "Драматичный закат в горах (Демо)": "Դրամատիկ մայրամուտ լեռներում (Դեմո)",
        "Ежемесячный доступ со всеми обновлениями.": "Ամսական մուտք բոլոր թարմացումներով:",
        "Если вы регистрировались на фотостоках через аккаунт Google или Apple, прямой вход по паролю этих сервисов не поддерживается для FTP/SFTP загрузки (это техническое ограничение самих стоков).": "Եթե գրանցվել եք ֆոտոստոկերում Google կամ Apple հաշվով, այս ծառայությունների գաղտնաբառով ուղիղ մուտքը չի աջակցվում FTP/SFTP վերբեռնման համար:",
        "Если при авторизации Google выдает ошибку 'invalid_client (401)', убедитесь, что вы создали Client ID в Google Cloud Console (APIs & Services -> Credentials).": "Եթե Google մուտքի ժամանակ ստանում եք 'invalid_client (401)' սխալ, համոզվեք, որ ստեղծել եք Client ID Google Cloud Console-ում:",
        "Еще не запускался": "Դեռ չի գործարկվել",
        "За последние 30 дней": "Վերջին 30 օրվա ընթացքում",
        "Забрать +5 фото": "Վերցնել +5 լուսանկար",
        "Заголовок": "Վերնագիր",
        "Заголовок фото": "Լուսանկարի վերնագիր",
        "Загружено": "Վերբեռնված է",
        "Загрузить все": "Վերբեռնել բոլորը",
        "Загрузить новый контент": "Վերբեռնել նոր բովանդակություն",
        "Загрузка видео по очереди (Строго 1 за 1)": "Տեսանյութերի հերթական վերբեռնում (Խիստ 1-ական)",
        "Загрузка видео по очереди включена": "Տեսանյութերի հերթական վերբեռնումը միացված է",
        "Загрузка видео по очереди отключена": "Տեսանյութերի հերթական վերբեռնումն անջատված է",
        "Загрузка медиафайлов...": "Մեդիաֆայլերի բեռնում...",
        "Загрузка файла": "Ֆայլի վերբեռնում",
        "Загрузка фото по очереди": "Լուսանկարների հերթական վերբեռնում",
        "Загрузка фото по очереди включена": "Լուսանկարների հերթական վերբեռնումը միացված է",
        "Загрузка фото по очереди отключена": "Լուսանկարների հերթական վերբեռնումն անջատված է",
        "Загрузка через ПК-сервер": "Վերբեռնում ՊԿ-սերվերի միջոցով",
        "Загрузка...": "Բեռնում...",
        "Загрузки": "Վերբեռնումներ",
        "Закрыть": "Փակել",
        "Заново": "Կրկին",
        "Заполнить ИИ": "Լրացնել ԱԻ-ով",
        "Заполнить все ИИ": "Լրացնել բոլորը ԱԻ-ով",
        "Запуск проверки...": "Ստուգման գործարկում...",
        "Запустить ИИ-анализ": "Գործարկել ԱԻ վերլուծություն",
        "Запустить проверку сейчас": "Գործարկել ստուգումը հիմա",
        "Запущен ИИ-анализ для": "Գործարկվել է ԱԻ վերլուծություն սրա համար՝",
        "Зарегистрироваться": "Գրանցվել",
        "ИИ": "ԱԻ Մոդելներ",
        "ИИ АНАЛИЗ": "ԱԻ ՎԵՐԼՈՒԾՈՒԹՅՈՒՆ",
        "ИИ Анализ": "ԱԻ Վերլուծություն",
        "ИИ для выбранных": "ԱԻ ընտրվածների համար",
        "ИИ провайдеры": "ԱԻ Մատակարարներ",
        "ИИ успешно заполнил метаданные для": "ԱԻ-ն հաջողությամբ լրացրեց մետատվյալները սրա համար՝",
        "ИИ-Ассистент": "ԱԻ-Օգնական",
        "Из буфера": "Սեղմատախտակից",
        "Изменить": "Փոխել",
        "Импорт видео и фото из архива Google Фото": "Վիդեոների և լուսանկարների ներմուծում Google Լուսանկարների արխիվից",
        "Импортировать": "Ներմուծել",
        "Импортировать в Google Фото": "Ներմուծել Google Լուսանկարներ",
        "Импортировать в очередь": "Ներմուծել հերթ",
        "Имя пользователя (логин)": "Օգտանուն (լոգին)",
        "Имя хоста (сервер)": "Հոսթի անուն (սերվեր)",
        "Инструкция Google Фото": "Google Լուսանկարների ուղեցույց",
        "Инструкция для Adobe Stock": "Հրահանգ Adobe Stock-ի համար",
        "Инструкция для Shutterstock": "Հրահանգ Shutterstock-ի համար",
        "Инструкция по настройке FTP для": "FTP կարգավորման հրահանգներ սրա համար՝",
        "Инструкция по настройке FTP для 123RF": "123RF-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для Adobe Stock": "Adobe Stock-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для Alamy": "Alamy-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для Depositphotos": "Depositphotos-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для Dreamstime": "Dreamstime-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для Freepik": "Freepik-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для Pond5": "Pond5-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для Shutterstock": "Shutterstock-ի համար FTP կարգավորման ուղեցույց",
        "Инструкция по настройке FTP для iStock / Getty": "iStock / Getty-ի համար FTP կարգավորման ուղեցույց",
        "Интегрированные фотостоки": "Ինտեգրված ֆոտոստոկեր",
        "Интеллектуальный Помощник": "Ինտելեկտուալ Օգնական",
        "Интеллектуальный ассистент": "Ինտելեկտուալ օգնական",
        "Интервал проверки": "Ստուգման միջակայք",
        "Интерфейс": "Ինտերֆեյս",
        "Интерфейс и Оформление": "Ինտերֆեյս և Ձևավորում",
        "Использовано диска:": "Օգտագործված սկավառակ՝",
        "Используется для прямого доступа к API Google Фото и Drive.": "Օգտագործվում է Google Լուսանկարների և Drive-ի API-ին ուղիղ մուտքի համար:",
        "Используйте ваш обычный личный аккаунт Google для входа в сервис.": "Ծառայություն մուտք գործելու համար օգտագործեք ձեր անձնական Google հաշիվը:",
        "История выгрузок": "Վերբեռնումների պատմություն",
        "История доходов": "Եկամուտների պատմություն",
        "История загрузок": "Վերբեռնումների պատմություն",
        "История пуста": "Պատմությունը դատարկ է",
        "КЛЮЧЕВЫЕ СЛОВА (Генерация ИИ)": "ԲԱՆԱԼԻ ԲԱՌԵՐ (ԱԻ Գեներացիա)",
        "Каждые": "Յուրաքանչյուր",
        "Как получить API-ключ": "Ինչպես ստանալ API բանալի",
        "Категории": "Կատեգորիաներ",
        "Категории (Макс. 2)": "Կատեգորիաներ (Առավ. 2)",
        "Категории не выбраны. Выберите до 2 категорий.": "Կատեգորիաներ ընտրված չեն։ Ընտրեք մինչև 2 կատեգորիա։",
        "Ключевые слова": "Բանալի բառեր",
        "Ключевые слова отсутствуют. Запустите ИИ-анализ.": "Բանալի բառերը բացակայում են։ Գործարկեք ԱԻ վերլուծություն։",
        "Коммерческий": "Կոմերցիոն",
        "Копировать": "Պատճենել",
        "Коэффициент (масштаб)": "Գործակից (մասշտաբ)",
        "Креативный": "Ստեղծագործական",
        "Кэш скачанных медиафайлов очищен!": "Ներբեռնված մեդիաֆայլերի քեշը մաքրված է։",
        "Кэширование включено": "Քեշավորումը միացված է",
        "Лимит достигнут": "Սահմանաչափը լրացված է",
        "Локальный ПК-сервер": "Լոկալ ՊԿ-սերվեր",
        "МЕТАДАННЫЕ": "ՄԵՏԱՏՎՅԱԼՆԵՐ",
        "Максимум продаж на стоках": "Առավելագույն վաճառքներ ստոկերում",
        "Мгновенное создание таблиц метаданных для любых агентств": "Մետատվյալների աղյուսակների ակնթարթային ստեղծում ցանկացած գործակալության համար",
        "Медиафайлов не найдено. Проверьте, включен ли Photos/Drive API в Google Cloud.": "Մեդիաֆայլեր չեն գտնվել: Ստուգեք՝ արդյոք Photos/Drive API-ն միացված է Google Cloud-ում:",
        "Меньше 2 МБ": "2 ՄԲ-ից պակաս",
        "Меньше 4 МБ (Рекомендуется)": "4 ՄԲ-ից պակաս (Խորհուրդ է տրվում)",
        "Меньше 8 МБ": "8 ՄԲ-ից պակաս",
        "Месячная подписка": "Ամսական բաժանորդագրություն",
        "Метаданные": "Մետատվյալներ",
        "Метрики": "Մետրիկաներ",
        "Мини": "Մինի",
        "Мой аккаунт": "Իմ հաշիվը",
        "НАВСЕГДА": "ԸՆԴՄԻՇՏ",
        "На удержании": "Պահման մեջ",
        "Награда получена! 🎉": "Պարգևը ստացված է! 🎉",
        "Награда через:": "Պարգևատրում՝",
        "Нажмите «Create API key»": "Սեղմեք «Create API key»",
        "Нажмите «Create Key», задайте имя и скопируйте сформированный токен.": "Սեղմեք «Create Key», տվեք անուն և պատճենեք գեներացված թոքենը:",
        "Нажмите для выбора или перетащите": "Հպեք ընտրելու համար կամ քաշեք այստեղ",
        "Нажмите кнопку «+ Create new secret key», укажите название и сохраните ключ.": "Սեղմեք «+ Create new secret key» կոճակը, նշեք անվանումը և պահպանեք բանալին:",
        "Нажмите на агентство ниже, чтобы зайти в личный кабинет через встроенный браузер.": "Հպվեք գործակալությանը ստորև՝ ներկառուցված բրաուզերով անձնական կաբինետ մուտք գործելու համար։",
        "Нажмите синюю кнопку «Create API key» (Создать ключ API) и выберите или создайте проект.": "Սեղմեք կապույտ «Create API key» կոճակը և ընտրեք կամ ստեղծեք նախագիծ:",
        "Название": "Վերնագիր",
        "Настроен": "Կարգավորված է",
        "Настройка Google Фото": "Google Լուսանկարների կարգավորում",
        "Настройки": "Կարգավորումներ",
        "Настройки сохранены!": "Կարգավորումները պահպանված են։",
        "Настройки стоков": "Ստոկերի կարգավորումներ",
        "Настройки стоков для фото": "Ստոկերի կարգավորումներ լուսանկարի համար",
        "Настройки успешно сохранены!": "Կարգավորումները հաջողությամբ պահպանվեցին։",
        "Настройте OAuth Consent Screen": "Կարգավորեք OAuth Consent Screen-ը",
        "Настройте ИИ для мгновенной индексации ваших кадров. Генерация коммерческих названий и SEO-тегов.": "Կարգավորեք ԱԻ-ն ձեր կադրերի ակնթարթային ինդեքսավորման համար: Կոմերցիոն անվանումների և SEO-թեգերի գեներացիա:",
        "Началась отправка": "Սկսվեց ուղարկումը՝",
        "Не выбрана": "Ընտրված չէ",
        "Не настроен": "Կարգավորված չէ",
        "Не подключено": "Միացված չէ",
        "Не удалось подключиться к App Store. Пожалуйста, проверьте интернет-соединение.": "Չհաջողվեց միանալ App Store-ին: Խնդրում ենք ստուգել ինտերնետ կապը:",
        "Не удалось получить доступ к папке": "Չհաջողվեց մուտք գործել թղթապանակ",
        "Недавние": "Վերջինները",
        "Некорректный формат Email": "Էլ. հասցեի անվավեր ձևաչափ",
        "Неограниченный импорт исходных медиафайлов прямо из облака": "Մեդիաֆայլերի անսահմանափակ ներմուծում անմիջապես ամպից",
        "Нет данных": "Տվյալներ չկան",
        "Нет загрузок": "Վերբեռնումներ չկան",
        "Нет новых файлов для ИИ-анализа.": "ԱԻ վերլուծության համար նոր ֆայլեր չկան։",
        "Нет подключённых стоков": "Միացված ստոկեր չկան",
        "Нет файлов, готовых к отправке.": "Ուղարկման պատրաստ ֆայլեր չկան:",
        "Нужна настройка": "Պահանջվում է կարգավորում",
        "ОБЛАКО GOOGLE ФОТО": "GOOGLE ԼՈՒՍԱՆԿԱՐՆԵՐԻ ԱՄՊ",
        "ОК": "OK",
        "Облачная синхронизация": "Ամպային սինխրոնացում",
        "Обмен кода авторизации...": "Վավերացման կոդի փոխանակում...",
        "Обнаружены данные для настройки": "Հայտնաբերվել են կարգավորման տվյալներ սրա համար՝",
        "Общий баланс": "Ընդհանուր հաշվեկշիռ",
        "Один платёж раз и навсегда. Без подписок.": "Մեկ վճարում ընդմիշտ: Առանց բաժանորդագրությունների:",
        "Ожидает подтверждения": "Սպասում է հաստատման",
        "Ок": "Լավ",
        "Описание": "Նկարագրություն",
        "Описание отсутствует": "Նկարագրությունը բացակայում է",
        "Отключено от Google Фото": "Անջատված է Google Լուսանկարներից",
        "Откройте Anthropic Console": "Բացեք Anthropic Console-ը",
        "Откройте Google AI Studio": "Բացեք Google AI Studio-ն",
        "Откройте OpenAI Platform": "Բացեք OpenAI Platform-ը",
        "Открытие окна авторизации Google...": "Google վավերացման պատուհանի բացում...",
        "Открыть Adobe Stock Contributor": "Բացել Adobe Stock Contributor",
        "Открыть Anthropic Console": "Բացել Anthropic Console-ը",
        "Открыть Google Cloud Console": "Բացել Google Cloud Console-ը",
        "Открыть OpenAI API Keys": "Բացել OpenAI API Keys-ը",
        "Открыть submit.shutterstock.com": "Բացել submit.shutterstock.com",
        "Отмена": "Չեղարկել",
        "Отправить": "Ուղարկել",
        "Отправить выбр.": "Ուղարկել ընտրվածները",
        "Отправить на стоки": "Ուղարկել ստոկեր",
        "Отправлено": "Ուղարկված է",
        "Очередь": "Հերթ",
        "Очередь выгрузки": "Վերբեռնման հերթ",
        "Очередь пуста": "Հերթը դատարկ է",
        "Очистить": "Մաքրել",
        "Очистить историю": "Մաքրել պատմությունը",
        "Очистить историю?": "Մաքրե՞լ պատմությունը:",
        "Очистка остаточного кэша": "Մնացորդային քեշի մաքրում",
        "Ошибка ИИ-анализа для": "ԱԻ վերլուծության սխալ սրա համար՝",
        "Ошибка выгрузки": "Վերբեռնման սխալ",
        "Ошибка загрузки": "Վերբեռնման սխալ",
        "Ошибка соединения с": "Միացման սխալ սրա հետ՝",
        "Ошибка сохранения папки:": "Թղթապանակի պահպանման սխալ՝",
        "Ошибка сохранения папки: ": "Թղթապանակի պահպանման սխալ՝ ",
        "Ошибка:": "Սխալ՝",
        "Ошибка: Нет активных стоков или не введены логин/пароль!": "Սխալ. Ակվիտ ստոկեր չկան կամ մուտքանունը/գաղտնաբառը լրացված չեն:",
        "Ошибки": "Սխալներ",
        "Ошибок": "Սխալներ",
        "ПРОГНОЗ ПОПУЛЯРНОСТИ (Рыночный анализ ИИ)": "ՊՈՊՈՒԼՅԱՐՈՒԹՅԱՆ ԿԱՆԽԱՏԵՍՈՒՄ (ԱԻ Շուկայական վերլուծություն)",
        "Пакетная обработка и загрузка сотен фото и 4K/8K видео без пауз и ограничений": "Հարյուրավոր լուսանկարների և 4K/8K վիդեոների խմբային մշակում և վերբեռնում առանց սահմանափակումների",
        "Память и Очистка кэша": "Հիշողություն և Քեշի մաքրում",
        "Папка для импорта": "Ներմուծման թղթապանակ",
        "Папка для сканирования": "Սկանավորման թղթապանակ",
        "Папка успешно выбрана:": "Թղթապանակը հաջողությամբ ընտրվեց՝",
        "Папка успешно выбрана: ": "Թղթապանակը հաջողությամբ ընտրվեց՝ ",
        "Параллельные потоки:": "Զուգահեռ հոսքեր՝",
        "Параллельные потоки: ": "Զուգահեռ հոսքեր՝ ",
        "Параметры": "Կարգավորումներ",
        "Параметры Google Фото": "Google Լուսանկարների կարգավորումներ",
        "Параметры SFTP / FTP для": "SFTP / FTP կարգավորումներ սրա համար՝",
        "Параметры выгрузки": "Վերբեռնման կարգավորումներ",
        "Параметры выгрузки и очередность": "Վերբեռնման կարգավորումներ և հերթականություն",
        "Параметры подключения": "Միացման Կարգավորումներ",
        "Параметры системы": "Համակարգի կարգավորումներ",
        "Пароль": "Գաղտնաբառ",
        "Пароль должен содержать не менее 6 символов": "Գաղտնաբառը պետք է պարունակի առնվազն 6 նիշ",
        "Перейдите в консоль разработчика Google Cloud и создайте новый бесплатный проект (например, SmartStock).": "Անցեք Google Cloud մշակողի կոնսոլ և ստեղծեք նոր անվճար նախագիծ (օրինակ՝ SmartStock):",
        "Перейдите в раздел «Агентства» и настройте учётные данные для Shutterstock, Adobe Stock или других стоков — статистика загрузок появится здесь автоматически.": "Անցեք «Գործակալություններ» բաժին և կարգավորեք Shutterstock-ի, Adobe Stock-ի կամ այլ ստոկերի տվյալները — վերբեռնումների վիճակագրությունը ավտոմատ կհայտնվի այստեղ։",
        "Перейдите на официальный портал Google AI Studio (aistudio.google.com).": "Անցեք Google AI Studio պաշտոնական պորտալ (aistudio.google.com):",
        "Перейдите на страницу ключей (console.anthropic.com/settings/keys).": "Անցեք բանալիների էջ (console.anthropic.com/settings/keys):",
        "Перейдите на страницу ключей API (platform.openai.com/api-keys).": "Անցեք API բանալիների էջ (platform.openai.com/api-keys):",
        "Перейти в настройки агентств →": "Անցնել գործակալությունների կարգավորումներին →",
        "Перейти на SmartStock PRO": "Անցնել SmartStock PRO-ի",
        "Планировщик": "Պլանավորող",
        "Планировщик выгрузки": "Վերբեռնման պլանավորող",
        "По стокам": "Ըստ ստոկերի",
        "Подготовка воспроизведения видео...": "Տեսանյութի նվագարկման պատրաստում...",
        "Подключение": "Միացում",
        "Подключение Google Фото": "Google Լուսանկարների միացում",
        "Подключено": "Միացված է",
        "Подключено к Google Фото": "Միացված է Google Լուսանկարներին",
        "Подключить": "Միացնել",
        "Подписка": "Բաժանորդագրություն",
        "Подписка продлевается автоматически, пока не будет отменена в настройках Apple ID не менее чем за 24 часа до окончания текущего периода.": "Բաժանորդագրությունն ավտոմատ երկարաձգվում է, քանի դեռ այն չի չեղարկվել Apple ID-ի կարգավորումներում ընթացիկ ժամանակաշրջանի ավարտից առնվազն 24 ժամ առաջ:",
        "Подробнее": "Մանրամասն",
        "Пожалуйста, введите API-ключ перед проверкой.": "Խնդրում ենք մուտքագրել API բանալին ստուգումից առաջ:",
        "Пожалуйста, введите ваш Google Client ID в параметрах системы.": "Խնդրում ենք մուտքագրել ձեր Google Client ID-ն համակարգի կարգավորումներում:",
        "Пожалуйста, введите логин и пароль.": "Խնդրում ենք մուտքագրել մուտքանունը և գաղտնաբառը:",
        "Пожизненный PRO": "Ցմահ PRO",
        "Позволяет отправлять фото через программу на вашем компьютере.": "Թույլ է տալիս ուղարկել լուսանկարներ համակարգչի ծրագրով:",
        "Позволяет отправлять фото через программу на вашем компьютере. Полезно, если на телефоне блокируется FTPS к Shutterstock.": "Թույլ է տալիս ուղարկել լուսանկարներ համակարգչի ծրագրով: Օգտակար է, եթե հեռախոսում արգելափակվում է FTPS-ը դեպի Shutterstock:",
        "Поздравляем! SmartStock PRO успешно активирован! 🎉": "Շնորհավորում ենք: SmartStock PRO-ն հաջողությամբ ակտիվացված է: 🎉",
        "Поиск по файлам...": "Փնտրել ֆայլերում...",
        "Поиск фото, альбомов...": "Լուսանկարների, ալբոմների որոնում...",
        "Показать все": "Տեսնել բոլորը",
        "Покупки": "Գնումներ",
        "Политика конфиденциальности": "Գաղտնիության քաղաքականություն",
        "Получить ключ в Google AI Studio": "Ստանալ բանալի Google AI Studio-ում",
        "Попробовать 3 дня бесплатно": "Փորձել 3 օր անվճար",
        "Порог срабатывания": "Գործարկման շեմ",
        "Порядок": "Կարգ",
        "Порядок очереди": "Հերթի կարգը",
        "Последний запуск": "Վերջին գործարկում",
        "Потоки параллельной загрузки": "Զուգահեռ վերբեռնման հոսքեր",
        "Пошаговое руководство по получению Client ID": "Քայլ առ քայլ ուղեցույց Client ID ստանալու համար",
        "Правовая информация и товарные знаки": "Իրավական տեղեկատվություն և ապրանքանիշեր",
        "Предел частоты кадров": "Կադրերի հաճախականություն",
        "При активации планировщика система будет проверять новые фото в выбранной папке и отправлять их в фоновом режиме.": "Պլանավորողն ակտիվացնելիս համակարգը կստուգի նոր լուսանկարները ընտրված թղթապանակում և կուղարկի դրանք ֆոնային ռեժիմում։",
        "При активации планировщика система будет проверять новые фото и отправлять их в фоновом режиме.": "Պլանավորողն ակտիվացնելիս համակարգը կստուգի նոր լուսանկարները և կուղարկի դրանք ֆոնային ռեժիմում։",
        "Приложение работает как прямой проводник: файлы отправляются без дублирования на диск телефона.": "Հավելվածն աշխատում է որպես ուղիղ ուղղորդիչ՝ ֆայլերը ուղարկվում են առանց հեռախոսում դուբլիկատավորման։",
        "Применить к фото": "Կիրառել լուսանկարի վրա",
        "Проверено": "Ստուգված է",
        "Проверить соединение": "Ստուգել միացումը",
        "Проверка ключа": "Բանալու ստուգում",
        "Проверка папки завершена!": "Թղթապանակի ստուգումն ավարտվեց։",
        "Проверка подключения к": "Միացման ստուգում դեպի՝",
        "Проверка соединения...": "Միացման ստուգում...",
        "Проверка...": "Ստուգում...",
        "Продолжить": "Շարունակել",
        "Продолжить с SmartStock PRO": "Շարունակել SmartStock PRO-ով",
        "Промпт для ИИ-анализа": "Հրահանգ ԱԻ վերլուծության համար",
        "Промпт определяет формат возвращаемого JSON-файла с заголовком и ключевыми словами.": "Հրահանգը սահմանում է վերադարձվող JSON ֆայլի ձևաչափը վերնագրով և բանալի բառերով։",
        "Размер": "Չափ",
        "Регистрация": "Գրանցում",
        "Редактировать": "Խմբագրել",
        "Режим проводника (Прямая выгрузка без кэша)": "Ուղղորդիչի ռեժիմ (Ուղիղ վերբեռնում առանց քեշի)",
        "Режим проводника активен: 0 МБ кэша": "Ուղղորդիչի ռեժիմն ակտիվ է՝ 0 ՄԲ քեշ",
        "Результаты анализа": "Վերլուծության արդյունքներ",
        "Рекомендуемый провайдер: самый быстрый и бесплатный доступ.": "Առաջարկվող մատակարար՝ ամենաարագ և անվճար մուտք:",
        "Репортажный": "Ռեպորտաժային",
        "Русский": "Русский",
        "Светлая": "Բաց",
        "Сводка активности": "Գործունեության ամփոփագիր",
        "Связь с App Store...": "Կապ App Store-ի հետ...",
        "Сервер выгрузки:": "Վերբեռնման սերվեր՝",
        "Сжатие JPEG перед загрузкой": "JPEG սեղմում վերբեռնումից առաջ",
        "Синхронизация": "Սինխրոնացում",
        "Синхронизация профиля активна": "Պրոֆիլի սինխրոնացումն ակտիվ է",
        "Синхронизация:": "Սինխրոնացում՝",
        "Синхронизация: ": "Սինխրոնացում՝ ",
        "Системная": "Համակարգային",
        "Системные уведомления": "Համակարգային ծանուցումներ",
        "Сканировать": "Սկանավորել",
        "Скопировано!": "Պատճենված է։",
        "Скопировать": "Պատճենել",
        "Скопировать все": "Պատճենել ամբողջը",
        "Скопируйте и вставьте ключ": "Պատճենեք և տեղադրեք բանալին",
        "Скопируйте ключ (начинается на «sk-...») и вставьте в поле OpenAI в настройках ИИ.": "Պատճենեք բանալին (սկսվում է «sk-...»-ով) և տեղադրեք հավելվածի OpenAI դաշտում:",
        "Скопируйте ключ (начинается на «sk-ant-...») и вставьте в поле Claude в настройках ИИ.": "Պատճենեք բանալին (սկսվում է «sk-ant-...»-ով) և տեղադրեք հավելվածի Claude դաշտում:",
        "Скопируйте полученный идентификатор (вида xxxx.apps.googleusercontent.com) и вставьте в поле Client ID в приложении.": "Պատճենեք ստացված նույնացուցիչը (տեսքը՝ xxxx.apps.googleusercontent.com) և տեղադրեք հավելվածի Client ID դաշտում:",
        "Скопируйте сгенерированный ключ (начинается на «AIzaSy...») и вставьте в приложении в поле Gemini.": "Պատճենեք գեներացված բանալին (սկսվում է «AIzaSy...»-ով) և տեղադրեք հավելվածի Gemini դաշտում:",
        "Создайте API-ключ": "Ստեղծեք API բանալի",
        "Создайте OAuth Client ID": "Ստեղծեք OAuth Client ID",
        "Создайте новый секретный ключ": "Ստեղծեք նոր գաղտնի բանալի",
        "Создайте проект в Google Cloud": "Ստեղծեք նախագիծ Google Cloud-ում",
        "Сохранить все настройки": "Պահպանել բոլոր կարգավորումները",
        "Сохранить изменения": "Պահպանել փոփոխությունները",
        "Спонсорский ролик": "Հովանավորչական հոլովակ",
        "Стандартный": "Ստանդարտ",
        "Статистика": "Վիճակագրություն",
        "Статистика очереди": "Հերթի վիճակագրություն",
        "Статус": "Կարգավիճակ",
        "Статус:": "Կարգավիճակ՝",
        "Стоки": "Ստոկեր",
        "Тема оформления": "Թեմա",
        "Темная": "Մութ",
        "У вас нет аккаунта?": "Չունե՞ք հաշիվ",
        "Увеличение 2x (Бикубическое)": "Մեծացում 2x (Բիկուբիկ)",
        "Увеличение 4x (Нейросеть)": "Մեծացում 4x (Նեյրոցանց)",
        "Удалить": "Ջնջել",
        "Удалить из очереди": "Հեռացնել հերթից",
        "Уже есть аккаунт?": "Արդեն ունե՞ք հաշիվ",
        "Условия использования (EULA)": "Օգտագործման պայմաններ (EULA)",
        "Успешная авторизация в Google": "Հաջող վավերացում Google-ում",
        "Успешная выгрузка": "Հաջող վերբեռնում",
        "Успешно": "Հաջողվել է",
        "Успешное соединение с сервером": "Հաջող միացում սերվերին",
        "Успешный вход через Apple!": "Հաջող մուտք Apple-ով",
        "Успешный вход через Google!": "Հաջող մուտք Google-ով",
        "Учетные данные обнаружены": "Մուտքային տվյալները հայտնաբերված են",
        "Файл": "Ֆայլ",
        "Файлы на устройстве": "Ֆայլեր սարքում",
        "Файлы не найдены": "Ֆայլեր չեն գտնվել",
        "Фоновая обработка завершена. Новых файлов загружено: ": "Ֆոնային մշակումն ավարտվեց։ Նոր վերբեռնված ֆայլեր՝ ",
        "Фоновый авто-сканер": "Ֆոնային ավտո-սկաներ",
        "Фоновый планировщик выгрузки": "Վերբեռնման ֆոնային պլանավորող",
        "Фото": "Լուսանկարներ",
        "Фотографии будут отправляться строго последовательно по одной.": "Լուսանկարները կուղարկվեն խիստ հերթականությամբ մեկ առ մեկ։",
        "Частота кадров изменена на ": "Կադրերի հաճախականությունը փոխվել է՝ ",
        "Частота кадров: ": "Կադրերի հաճախականություն՝ ",
        "Экспорт CSV и метаданных": "CSV և մետատվյալների արտահանում",
        "Эффективность агентств": "Գործակալությունների արդյունավետությունը",
        "Язык изменён на Русский": "Լեզուն փոխվեց Ռուսերենի",
        "Язык интерфейса": "Ինտերֆեյսի լեզու",
        "Язык приложения": "Հավելվածի լեզու",
        "всего": "ընդհանուր",
        "готовность": "պատրաստվածություն",
        "загрузок": "վերբեռնումներ",
        "записей": "գրանցումներ",
        "из": "-ից",
        "или": "կամ",
        "подключено": "միացված է",
        "поток": "հոսք",
        "потока": "հոսք",
        "потоков": "հոսք",
        "успешно загружен на стоки!": "հաջողությամբ վերբեռնվեց ստոկեր։",
        "успешно загружен!": "հաջողությամբ վերբեռնվեց։",
        "файлов...": "ֆայլեր...",
        "час": "ժամ",
        "часа": "ժամ",
        "часов": "ժամ"
    ]
    
    /// Потокобезопасный перевод строки с синхронизацией через NSLock
    static func translate(_ text: String, to lang: String) -> String {
        guard lang != "Русский" && !text.isEmpty else {
            return text
        }
        
        lock.lock()
        defer { lock.unlock() }
        
        let dict = (lang == "Հայերեն" || lang == "Armenian") ? hyTranslations : enTranslations
        
        // 1. Точное совпадение по словарю
        if let translation = dict[text] {
            return translation
        }
        
        // 2. Безопасная обработка префиксов для динамических шаблонов
        let dynamicPrefixes = [
            "Частота кадров: ",
            "Частота кадров изменена на ",
            "Параллельные потоки: ",
            "Язык изменён на ",
            "Файл ",
            "Началась отправка ",
            "Ошибка соединения с ",
            "Синхронизация: ",
            "Инструкция по настройке FTP для ",
            "Обнаружены данные для настройки ",
            "Вход через ",
            "Проверка подключения к ",
            "Добавлен файл из Google Фото: ",
            "Добавлен файл: ",
            "Загружено фото: ",
            "Фоновая обработка завершена. Новых файлов загружено: ",
            "Импортировано из Google Фото: ",
            "Ошибка импорта ",
            "Всего файлов: "
        ]
        
        for prefix in dynamicPrefixes {
            if text.hasPrefix(prefix) {
                let translatedPrefix = dict[prefix] ?? prefix
                let remainder = String(text.dropFirst(prefix.count))
                let translatedRemainder = dict[remainder] ?? remainder
                return translatedPrefix + translatedRemainder
            }
        }
        
        return text
    }
}
